### ISSUE TITLE
Another chat bug

### ISSUE THREAD

**Issue by DanielContreras** [ElvUI-TBC/ElvUI#100]
This is something I noticed initially, but I forgot to mention it with the previous chat problems; It seems whenever the UI is reloaded , this includes logging in, some chat that happened earlier is loaded. I've seen up to ~6 messages from previous parties show up.

**Comment by TIGJERUX** [comment]
thats a bonus if ive ever seen one. :D

**Comment by crumdidlyumshis** [comment]
![wowscrnshot_060617_232059_ink_li](https://user-images.githubusercontent.com/7307335/26862238-35f6d10a-4b0f-11e7-888c-3c2e1456d5d9.jpg)
