### ISSUE TITLE
I'm not able to change poison / enchants

### ISSUE THREAD

**Issue by CryingEnder** [ElvUI-TBC/ElvUI#107]
Hello. A problem that this interface has is that on my rogue I'm not able to change poisons on weapons or to enchant my armor (with the armor bonus from leatherworking). I can ONLY enchant them or add poison when the items don't have any enchants already. For example I need to remove my poison from weapons first and then add it. For the armor, I have to disable Elvui to change the enchant. That's all because the "Yes" button of the window that asks you if you want to change X to Y doesn't work. I think it works like a "No".

**Comment by Shamainy** [comment]
Can confirm this aswell. Have same issue on my rogue.
