### ISSUE TITLE
Key Press / Buff Indicators

### ISSUE THREAD

**Issue by Reevan1337** [ElvUI-TBC/ElvUI#110]
1. Press on Key down function not working
2. Unit Frames: Group and Raid Frames, Buff Indicators not working

**Comment by Supernoodles1990** [comment]
Can confirm no party frames or raid frames and also not seeing debuffs above enemies unitframes so no rend etc

**Comment by Supernoodles1990** [comment]
Party Frames and Debuffs on unitframes are back for me @Reevan1337 needs to recheck to confirm

**Comment by lishpeth** [comment]
I can confirm the buff indicators and raiddebuff indicators are not working. I have added some spell id's and they didn't show up on party/raid frames. The id that I have used was belong to rejuvenation's in game id provided by elvui.
