### ISSUE TITLE
Error when changing a channel color

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#112]
Message: Interface\FrameXML\ChatConfigFrame.lua:975: attempt to index global 'CHATCONFIG_SELECTED_FILTER_SETTINGS' (a nil value)
Time: 06/06/17 19:06:31
Count: 1
Stack: [C]: ?
Interface\FrameXML\ChatConfigFrame.lua:975: in function `CombatConfig_Colorize_Update'
Interface\FrameXML\ChatConfigFrame.lua:1257: in function `func'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>
[C]: ?

**Comment by crumdidlyumshis** [comment]
cannot reproduce :(

**Comment by devellio** [comment]
Can confirm - get this as well. The color changes, but the error still pops up.
