### ISSUE TITLE
Druid stealth Actionbar Paging

### ISSUE THREAD

**Issue by AnaS90** [ElvUI-TBC/ElvUI#120]
Hey guys,

appreciate your amazing work first of all! I got the issue, that my actionbar in cat form does not switch, when entering stealth. Is there a way to fix this? some1 with the same problem?

**Comment by Ellypsis63** [comment]
Exact same problem here, when using prowl ( stealth ) the action bar doesn't switch to stealth  bar, that's really frustrating
