### ISSUE TITLE
it be better mate

### ISSUE THREAD

**Issue by sckush** [ElvUI-TBC/ElvUI#121]
Message: Interface\AddOns\Blizzard_TalentUI\Localization.lua:5: attempt to index a nil value
Time: 06/09/17 17:27:21
Count: 1
Stack: [C]: ?
Interface\AddOns\Blizzard_TalentUI\Localization.lua:5: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:927: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:264: in function <Interface\FrameXML\UIParent.lua:263>
[C]: in function `TalentFrame_LoadUI'
Interface\FrameXML\UIParent.lua:295: in function `ToggleTalentFrame'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

**Comment by Loaal** [comment]
Duplicate #125
