### ISSUE TITLE
Some random plates/lists.

### ISSUE THREAD

**Issue by Aszjune** [ElvUI-TBC/ElvUI#123]
eh need help with this, how to remove those plates/lists?
https://gyazo.com/32ab014c1051abd5771ff314071e1e29

**Comment by Shamainy** [comment]
What kind of list are those?

**Comment by Loaal** [comment]
1. Make sure **!DebugTools** enabled
2. Type **/fstack** in the chat
3. Point mouse at the problem frame
4. Take screenshot (for each frame)
![capture](https://cloud.githubusercontent.com/assets/590348/22017108/f1c563a2-dcb9-11e6-8b27-a10347af1d32.PNG)
