### ISSUE TITLE
old issues need help 

### ISSUE THREAD

**Issue by sckush** [ElvUI-TBC/ElvUI#125]
Message: Interface\AddOns\Blizzard_TalentUI\Localization.lua:5: attempt to index a nil value
Time: 06/09/17 23:28:50
Count: 1
Stack: [C]: ?
Interface\AddOns\Blizzard_TalentUI\Localization.lua:5: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:927: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:264: in function <Interface\FrameXML\UIParent.lua:263>
[C]: in function `TalentFrame_LoadUI'
Interface\FrameXML\UIParent.lua:295: in function `ToggleTalentFrame'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Message: Interface\AddOns\ElvUI\modules\misc\misc.lua:99: attempt to call upvalue 'GetCoinTextureString' (a nil value)
Time: 06/09/17 23:35:35
Count: 2
Stack: (tail call): ?
Interface\AddOns\ElvUI\modules\misc\misc.lua:99: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function a<...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Loaal** [comment]
What's your client language?

**Comment by sckush** [comment]
chinese

**Comment by Loaal** [comment]
1. Exit the game
2. Delete folder addon with name "**Blizzard_TalentUI**" `Wow\Interface\AddOns\Blizzard_TalentUI`
or all addons starting with "**Blizzard_**"
3. Start the client
4. There is no error
