### ISSUE TITLE
Threat not showing on nameplate

### ISSUE THREAD

**Issue by Efemer2k** [ElvUI-TBC/ElvUI#127]
As the title says the nameplate doesn`t reflect your actual threat on the target. Dunno if tanked target color is working either.
![threat](https://user-images.githubusercontent.com/28844276/27000301-2dba62e0-4db7-11e7-9c0d-775251ba9cf3.png)

**Comment by lishpeth** [comment]
I dont have the threat section with my Elvui, may it be because I have chose healer layout?

**Comment by Loaal** [comment]
That's because of threat options is temporarily hidden
