### ISSUE TITLE
Talking to a Vendor with repair capabilities (Krinkle Goodsteel in Gadgetzan)

### ISSUE THREAD

**Issue by Larsy93** [ElvUI-TBC/ElvUI#128]
Message: Interface\AddOns\ElvUI\modules\misc\misc.lua:99: attempt to call upvalue 'GetCoinTextureString' (a nil value)
Time: 06/10/17 09:56:21
Count: 1
Stack: (tail call): ?
Interface\AddOns\ElvUI\modules\misc\misc.lua:99: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Larsy93** [comment]
All my equipment was fully red at the time if that matters

**Comment by Loaal** [comment]
Update ElvUI, that bug already fixed 2f23c24
