### ISSUE TITLE
Custom Chat window title dissapears

### ISSUE THREAD

**Issue by Larsy93** [ElvUI-TBC/ElvUI#129]
When i press log or the whisper tab itself it just dissapears.

https://i.gyazo.com/ce4348bc5515d3b12e960fe36a916fd0.png

https://i.gyazo.com/97401d6881135899f56978cc15b10feb.png

It does go into that tab but the title goes away, so i cant go from log to whisper. I can however go to whisper from general

**Comment by DanielContreras** [comment]
Also to add to this; you cannot drag the custom tab to the other side where "Loot / Trade" tab is. Granted, I'm not sure if that's how it's meant to be.

**Comment by Redtuzk** [comment]
Getting the same thing
