### ISSUE TITLE
Feral Druid, No Stealth Bar

### ISSUE THREAD

**Issue by Ellypsis63** [ElvUI-TBC/ElvUI#133]
When entering in stealth as Feral druid, the action bar doesn't change to stealth bar, really frustrating.

**Comment by w9nder** [comment]
Can Confirm. 

Can you check if you can use "Actionbar 2?" Because i cant. It is there but i cannot use it.

**Comment by Shamainy** [comment]
Stealth bar works for rogue's, didn't work before but they fixed for rogues atleast. Suppost it's easy fix for druids aswell. Action Bar 2 still bugged out tho.

**Comment by Kafistal** [comment]
In TBC druids didn't have stealth bars. The way stance bars are handled, it is not really possible to do druid stealth bar. You can use macros to change skills when you are in stealth or not.
