### ISSUE TITLE
Aurabuffs messed up after latest commits

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#135]
They aren't linked correctly and show remaining buff times from other spells (for example: battleshout 9:45min left from blessing of salvation)

**Comment by tankey123** [comment]
Yep and debuffs timers on your target have the same problem after the most recent update.

**Comment by fatlus** [comment]
Still buggy :/
![wowscrnshot_061117_225636](https://user-images.githubusercontent.com/6052285/27014452-af21da8c-4ef9-11e7-82e9-b0ec5732d48a.jpg)

**Comment by fatlus** [comment]
I don't know if this helps: The spell should be linked correctly because the aurabuffs still shows the amount of stackable buffs (water shield for example).

**Comment by fatlus** [comment]
Is there a solution? Actually it is really hard to play without the working aurabuffs

**Comment by fatlus** [comment]
Looks good for me after latest commits
