### ISSUE TITLE
[BUG] - Bar 2 still not visable

### ISSUE THREAD

**Issue by Shamainy** [ElvUI-TBC/ElvUI#139]
It's like Bar 2 is there, but you can't see it, if I activate Backdrop you can see where the action bar is suppost to be but you not able to make any use of it since you can only see the Backdrop and not the actionbar buttons themself.

**Comment by Redtuzk** [comment]
I've found that you've gotta enable the individual actionbars in the blizz Interface menu, just toggling the bars on/off in the ElvUI config won't do it

**Comment by Shamainy** [comment]
I see, ok!
