### ISSUE TITLE
Player Frame - Players buffs not showing

### ISSUE THREAD

**Issue by Shamainy** [ElvUI-TBC/ElvUI#140]
http://imgur.com/a/cuGtV

As you can see on this pic the buffs doesn't show up on players even tho they are enable, but they do show up on target frame buffs.

**Comment by palenius** [comment]
bumb! i have same problem

**Comment by Bunny67** [comment]
Check

**Comment by crumdidlyumshis** [comment]
Appears to work fine now. Closing
