### ISSUE TITLE
Hunter pet happiness icon missing

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#145]
The unit frame of the hunter pet should have a small icon with the pet hapiness (green, yellow, red).

**Comment by crumdidlyumshis** [comment]
This is actually how it is supposed to be. Take a look at a closed issue from wrath version: https://github.com/ElvUI-WotLK/ElvUI/issues/9

**Comment by fatlus** [comment]
Ok, solved it with your solution.
closed
