### ISSUE TITLE
Minimap distance always at default after new login

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#146]
I play with max distance of the minimap and i must always scroll out after a new login

**Comment by crumdidlyumshis** [comment]
I've tried multiple characters, different settings, reset to default, and still cannot reproduce this. Are you sure you don't have the option to automatically reset zoom enabled? It's under the maps tab in ElvUI. Then go to minimap options.

**Comment by fatlus** [comment]
Yeah, I never enabled this option. I don't know why this happens, maybe I need a complete reset with deleting the lua

**Comment by crumdidlyumshis** [comment]
Fixed? Close?

**Comment by fatlus** [comment]
Not for me but it seems I am the only one with the problem. I removed the elvui.lua on a char but after a relog it is again at the default value.

**Comment by fatlus** [comment]
I spoke with another ElvUI users on my server and they have the same problem

**Comment by Kapuzenjoe** [comment]
Hi, i had the same problem. But after i enabled auto reset zoom it goes always to max distance.

**Comment by crumdidlyumshis** [comment]
Check latest and see if problem still persists.

**Comment by fatlus** [comment]
Doesn't fix this issue :/

**Comment by Loaal** [comment]
@fatlus please check if problem still persists.

**Comment by fatlus** [comment]
Looks good so far!

**Comment by fatlus** [comment]
I think the pleasure was too early, I must scroll again :(. I noticed that this bug only occures when wow.exe is completly shut down. Log out and log in without quitting WoW saves the minimap zoom settings.

**Comment by fatlus** [comment]
It works!
