### ISSUE TITLE
Missing health values

### ISSUE THREAD

**Issue by Redtuzk** [ElvUI-TBC/ElvUI#147]
Anyone not in my party aswell as friendly and hostile NPCs shows as having a healthvalue of 100.
Whenever someone joins my party their health value is picked up correctly.

http://i.imgur.com/rg3XAY6.png

**Comment by Shamainy** [comment]
Had that problem for long time when this came out as new. But now past 4-5 updates I do have the right HP value for Enemy NPCs, donu about party yet tho, but guess it works too.. Maby something on your end?

**Comment by Redtuzk** [comment]
@Shamainy 

Yea, not sure. I'm on the latest version and got no other conflicting addons.
Also tried loading different profiles, but the issue persist.

In any case, I really appreciate the work you're putting in with the multiple daily commits @Bunny67 👍

**Comment by Shamainy** [comment]
And you have " [healthcolor][health:current-percent] " as your Text Format on target fram?

**Comment by Redtuzk** [comment]
I do.

**Comment by Loaal** [comment]
I guess that's all what we can do with that problem

**Comment by crumdidlyumshis** [comment]
Mobhealth 3 implementation?

**Comment by Redtuzk** [comment]
Appreciate it @Loaal , it seems to _kinda_ have worked.
Sometimes it's there and sometimes it's not, no LUA errors or nothing though.

**Comment by crumdidlyumshis** [comment]
@Redtuzk Basically in Vanilla and TBC, mob health and player health was more-less a non-existent thing until Mobhealth library was introduced. This didn't exactly give you a precise measurement as to who has 123k or 100 health. It did calculations, cached info, made guesstimations based on many criteria like player/mob level, type, class, spells, how much health was used, etc... So its not going to be 100% exactly to say each time, but it will be pretty dang close for the most part each time.

**Comment by Redtuzk** [comment]
@crumdidlyumshis Alright, I thought something like that might've been the case, but I thought they had fixed it by the time TBC came out. Appreciate the answer!
