### ISSUE TITLE
TEMPORARY fix for castbar on nameplates - How to take it away for now.

### ISSUE THREAD

**Issue by Shamainy** [ElvUI-TBC/ElvUI#148]
Go in WoW's interface, then Combat, then uncheck "Cast Bars" On Nameplates.

**Comment by Larsy93** [comment]
I noticed that some spells the progressbar works but Numbers are Still off, the furlborgs in teldrassil that cast wrath had a working green progressbar

**Comment by Shamainy** [comment]
Ye, but thats still annoying to watch, rather just have castbar on the main enemy frame for now only.

**Comment by dishnua** [comment]
I just disabled nameplates altogether, using Class Colored Nameplates Addon + Gladdy Castbar (in nameplates option)
