### ISSUE TITLE
Mouse view tempo @ lowest value after afk logout

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#153]
After the 30min auto logout after being 30min afk the mouse view tempo (not sure what's the correct spelling in english because of german client) is at the lowest value

**Comment by Ditchbitch** [comment]
have the same problem - why is that?

**Comment by Loaal** [comment]
Make sure you use latest version.

**Comment by fatlus** [comment]
The problem happens again, now after returning from being AFK

**Comment by fatlus** [comment]
Not happened again, closed for now
