### ISSUE TITLE
Raid Frames not possible to target

### ISSUE THREAD

**Issue by Ditchbitch** [ElvUI-TBC/ElvUI#157]
When joining a raid I can't target the raid member. Please help :)

**Comment by Bunny67** [comment]
Can you describe the problem in more detail?

**Comment by crumdidlyumshis** [comment]
Just to make sure, have you updated to the latest ElvUI and ElvUI_Config version? This should have already been fixed via #122

**Comment by Ditchbitch** [comment]
I'm joining a raid and the raidframes show up on the left side of my interface, but it's impossible to choose single raidmember. I can't click on them only hover and the tooltip shows.

I'm using ElvUI Version 1.30 (shown at top of the Config)

**Comment by Ditchbitch** [comment]
is this the correct version?

**Comment by crumdidlyumshis** [comment]
Well it is, however there have been many updates since then. I would redownload the latest version and test again.

**Comment by Ditchbitch** [comment]
Another (maybe) dumb question. For updating ElvUI I only download the zip-file and replace the ElvUI and ElvUI Config folders? 😳

**Comment by Larsy93** [comment]
You replace all folders

**Comment by Ditchbitch** [comment]
I redownloaded replaced all folders and it's still not working :(

**Comment by Ditchbitch** [comment]
oh my god thank u so much it's working :)
keep up the good work have a nice weekend :)
