### ISSUE TITLE
Error Code with WIM addon

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#158]
[2017/06/14 17:18:36-107-x1]: ElvUI-1.30\modules\chat\chat.lua:770: bad argument #1 to 'strlen' (string expected, got nil)
ElvUI-1.30\modules\chat\chat.lua:770: in function `ChatFrame_MessageEventHandler'
ElvUI-1.30\modules\chat\chat.lua:953: in function `ChatFrame_OnEvent'
ElvUI-1.30\modules\chat\chat.lua:959: in function <Interface\AddOns\ElvUI\modules\chat\chat.lua:958>

---

Hi, i get this Error when my WIM addon is on, it happens since the last Update for chat.lua .

**Comment by Bunny67** [comment]
fixed
