### ISSUE TITLE
right and left frame (chat) doesnt work

### ISSUE THREAD

**Issue by tjukoela** [ElvUI-TBC/ElvUI#16]
Both of frame does not display anything, they are just empty

**Comment by crumdidlyumshis** [comment]
I just want to say thank you for reporting these issues! Keep reporting and we will keep researching and fixing 👍

**Comment by crumdidlyumshis** [comment]
@Bunny67 I have tried many different ways to get the chat frames working on my local. Do you have any update on this? I think the frames have to be mostly re-written.

**Comment by crumdidlyumshis** [comment]
update to latest, most of the chat functionality is working now, few more minor errors to tackle. :)
