### ISSUE TITLE
ZOMGbuffs error after latest commits

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#160]
Message: Interface\AddOns\ZOMGBuffs\ZOMGBuffs.lua:5070: bad argument #1 to 'strsub' (string expected, got table)
Time: 06/14/17 19:12:36
Count: 1
Stack: [C]: ?
[C]: in function `strsub'
Interface\AddOns\ZOMGBuffs\ZOMGBuffs.lua:5070: in function `filterFunc'
Interface\AddOns\ElvUI\modules\chat\chat.lua:761: in function `ChatFrame_MessageEventHandler'
Interface\AddOns\ElvUI\modules\chat\chat.lua:953: in function `ChatFrame_OnEvent'
Interface\AddOns\ElvUI\modules\chat\chat.lua:959: in function <Interface\AddOns\ElvUI\modules\chat\chat.lua:958>

**Comment by Bunny67** [comment]
fixed
