### ISSUE TITLE
Threat bar - missing

### ISSUE THREAD

**Issue by Svetdwell** [ElvUI-TBC/ElvUI#163]
On the 3.3.5 version there was a threat gauge that pops up while in a boss encounter on the right datatext panel. It would be really handy if it was implemented here.

**Comment by Loaal** [comment]
On the 3.3.5 we can get threat information for player target via wow api.
On the 2.4.3 we can do it only by using huge library which will calculate threat value by scanning combat log events, it's high resource-dependent and pointless for just one small bar.
Probably it will be implemented later.

**Comment by crumdidlyumshis** [comment]
Maybe with https://www.wowace.com/projects/threat-2-0/files/300111

**Comment by Loaal** [comment]
Fixed with 32b9961

> Module depending on [Threat-2.0](https://www.wowace.com/projects/threat-2-0/files) library which doesn't bundled with ElvUI
