### ISSUE TITLE
Unit Frame debuffs not working

### ISSUE THREAD

**Issue by DJMarxman** [ElvUI-TBC/ElvUI#165]
Version 1.30 downloaded today, neither me nor a friend are able to get debuffs working on target frame. Buffs work fine, but debuffs refuse to display. Red circle indicates where debuffs should be appearing on this unit frame, but they don't.

![capture](https://user-images.githubusercontent.com/29473466/27211940-b3fc2bf0-522a-11e7-9069-6e4390efdbe4.PNG)

**Comment by DJMarxman** [comment]
This is still broken as of the June 16th build.

**Comment by palenius** [comment]
Bump!

**Comment by DJMarxman** [comment]
Still broken as of v1.31 June 17th.

**Comment by palenius** [comment]
Bumb! Still broken

**Comment by Bunny67** [comment]
![wowscrnshot_061817_145151](https://user-images.githubusercontent.com/5816685/27260473-be31ddc4-5435-11e7-8f40-c9e4a7285128.jpg)

**Comment by palenius** [comment]
Player frame debuffs are working fine. Target frame debuffs wont show.

**Comment by Bunny67** [comment]
![wowscrnshot_061817_150158](https://user-images.githubusercontent.com/5816685/27260532-1ae43020-5437-11e7-850e-3137dc2aa8c6.jpg)
Temporarily use this way

**Comment by palenius** [comment]
I got it showing. It was showing all the time but the icon size was one pixel?????

**Comment by palenius** [comment]
I mean it was showing after I did what u screen shotted

**Comment by palenius** [comment]
but the debuff icons are gray, not colour

**Comment by Bunny67** [comment]
![wowscrnshot_061817_152455](https://user-images.githubusercontent.com/5816685/27260676-57bda438-543a-11e7-9a9d-8dec7d51ea00.jpg)
donwload last updates
