### ISSUE TITLE
Any chance of getting ElvUI_Bunny ported over?

### ISSUE THREAD

**Issue by Larsy93** [ElvUI-TBC/ElvUI#169]
Or atleast the character frame and stuff, would be amazing.

**Comment by Larsy93** [comment]
And perhaps minimap buttons

**Comment by crumdidlyumshis** [comment]
ElvUI_MinimapButtons -> https://github.com/ElvUI-TBC/ElvUI_MinimapButtons

😄

**Comment by crumdidlyumshis** [comment]
ElvUI_Bunny features are now all within ElvUI_Enhanced. Enjoy! https://github.com/ElvUI-TBC/ElvUI_Enhanced

**Comment by Bunny67** [comment]
:(

**Comment by Larsy93** [comment]
:( i feel you bunny, but thank u so much guys, character screen and everything, amazeballs. Some credit to Bunny wouldnt be wrong tho 🥇

**Comment by crumdidlyumshis** [comment]
Oh I'm not taking any credit for anything! I am just here to help out with anything I can. @Bunny67 deserves a gold metal! And so do the other guys like @Apollyonn and @Loaal :D
