### ISSUE TITLE
Pet bar

### ISSUE THREAD

**Issue by tjukoela** [ElvUI-TBC/ElvUI#17]
Pet bar doesnt appear when we summon the pet

**Comment by rusonn** [comment]
Yep, also not possible to see when pet is hungry. Would like to use the UI but can't as I main hunter, very nice otherwise. :-)

**Comment by crumdidlyumshis** [comment]
You can use it now, however, something is missing with the icon textures. So for now, its blank icons. Sorry. Will keep working on it.

**Comment by rusonn** [comment]
Thanks dude! Would be cool if you could add a function to see the pets hunger level, maybe a border on the pet hp bar which either is green, yellow or red?
