### ISSUE TITLE
System Messages

### ISSUE THREAD

**Issue by trav346** [ElvUI-TBC/ElvUI#170]
System messages not showing in chat despite being turned on in chat settings

**Comment by trav346** [comment]
Somehow my settings for ElvUI prevented me from seeing this but doing a manual reset fixed this issue.

**Comment by trav346** [comment]
Since accepting a quest, system messages are not working again. See screenshot of error:

http://i.imgur.com/hTnDDMy.png

**Comment by hernberg** [comment]
Accepting quest for me doesnt show in chat frame for me aswell... I dont get error message tho. But it aint showing. Etc "Quest accepted: Jidderish Jiddersih"

**Comment by trav346** [comment]
Latest build (fix for 178) seems to have also fixed system messages once again.
