### ISSUE TITLE
Pet Frame

### ISSUE THREAD

**Issue by trav346** [ElvUI-TBC/ElvUI#171]
No option to display hunter pet happiness on Pet Frame or as aura.

**Comment by crumdidlyumshis** [comment]
#145

**Comment by crumdidlyumshis** [comment]
Is this in regards to the pet frame or pet unit frame?

**Comment by trav346** [comment]
Oh, thank you for this!

**Comment by trav346** [comment]
Personal pet frame that would otherwise always display with your hunter.

**Comment by crumdidlyumshis** [comment]
Gotcha! Well hope the info I gave helped. :)
