### ISSUE TITLE
Barupdate

### ISSUE THREAD

**Issue by snackyy** [ElvUI-TBC/ElvUI#173]
All bars work fine expect Bar1 wich worked fine 1 update before ?? what was the issue for updating this ? :D

**Comment by DJMarxman** [comment]
My bar 1 works fine, but the Blizzard action bar texture is stuck enabled underneath my elv bars.

**Comment by fatlus** [comment]
Add this for a hotfix at the end of the actionbars.lua:

MainMenuBarTexture2:Hide()
MainMenuBarTexture3:Hide()

**Comment by Loaal** [comment]
fixed 6507331
