### ISSUE TITLE
Nameplates - Font Not Set

### ISSUE THREAD

**Issue by dishnua** [ElvUI-TBC/ElvUI#176]
Message: ...rface\AddOns\ElvUI\modules\nameplates\nameplates.lua:367: <unnamed>:SetText(): Font not set
Time: 06/17/17 06:19:30
Count: 3
Stack: (tail call): ?
[C]: ?
[C]: in function `SetText'
...rface\AddOns\ElvUI\modules\nameplates\nameplates.lua:367: in function <...rface\AddOns\ElvUI\modules\nameplates\nameplates.lua:354>

**Comment by Tristan000** [comment]
Message: ...rface\AddOns\ElvUI\modules\nameplates\elements\healthBar.lua:107: :SetText(): Font not set
Time: 06/17/17 17:00:12
Count: 32
Stack: (tail call): ?
[C]: ?
[C]: in function `SetText'
