### ISSUE TITLE
action bar visual bug. 

### ISSUE THREAD

**Issue by kage21** [ElvUI-TBC/ElvUI#178]
after getting my first key this appeared 
![image](https://user-images.githubusercontent.com/29508269/27255054-d5520484-5363-11e7-8970-5fcdd8ee3f5b.png) and i couldnt get it to go away even after losing the key it is still there idk if it has to do with the key or if something with the AB just broke but disabling the AB's and going back to vanilla AB's fixes it, i also tried disabling it and using bongos and that fixes it as well so it has somthing to do with the actionbars within elvui. thats never happend before until i got my first key

**Comment by kage21** [comment]
update i tried installing the latest version and it is still there

**Comment by kage21** [comment]
nvm i fixed it

**Comment by trav346** [comment]
How did you fix it? I'm still getting it even after resetting all settings.

**Comment by kage21** [comment]
@trav346 put 
MainMenuBarTexture2:Hide()
MainMenuBarTexture3:Hide() 
at the bottom of the actionbars.lua file like this and it fixed it for me. found it in another post for a diferent/similar reason and and thought to try it and it worked for me
![image](https://user-images.githubusercontent.com/29508269/27255426-68d922c0-536c-11e7-90d5-30d93d597aab.png)

**Comment by trav346** [comment]
Excellent. Thanks!

**Comment by denellum** [comment]
Worked for me as well! Thanks!
