### ISSUE TITLE
2 loot frames

### ISSUE THREAD

**Issue by TIGJERUX** [ElvUI-TBC/ElvUI#190]
Loot Frame annd Loot /Alert Frames (Grow Up) 

Loot frames aren't working.

**Comment by crumdidlyumshis** [comment]
Can you describe what exactly happened and/or paste an error that occured? :)

**Comment by TIGJERUX** [comment]
Sorry for the late response, theres just 2 loot frames and one of them is just not working, no errors no nothing.

https://gyazo.com/804255fb6a6c6a301f596bd2f9d6ccfb

The top one (Loot Frame) is not working, just basically a waste of box I think.

however the Loot / Alert Frames (Grow Up) are working perfectly fine.

**Comment by Loaal** [comment]
Loot Frame mover appears if "Open Loot Window at Mouse" option is disabled.

**Comment by TIGJERUX** [comment]
Oh, alright, thank you.
