### ISSUE TITLE
Chat panel /who

### ISSUE THREAD

**Issue by kinappy** [ElvUI-TBC/ElvUI#195]
When typing /who in the chat panel the character is not returned but Added "/who <char name>" to queue

I restored back to an earlier version and there it's working ok.
![screenshot](https://user-images.githubusercontent.com/25764850/27348311-d9021d7a-55f3-11e7-8611-0b7de528f83e.JPG)

**Comment by kinappy** [comment]
I noticed afterwards when trying again it eventually comes back with a timeout
![screenshot1](https://user-images.githubusercontent.com/25764850/27349173-b89da77c-55f6-11e7-8cff-d2316280c328.JPG)

**Comment by Bunny67** [comment]
Try to disabled all addons excluding:

!Compatibility
!DebugTools
ElvUI
ElvUI_Config

**Comment by kinappy** [comment]
Still the same.

I made a copy of my game folder, deleted cache, interface and WTF.

Started WoW and made sure /who was working which was OK.

Installed only the four folder mentioned above which I just downloaded again.

Restarted and /who has the same issue.

![screenshot2](https://user-images.githubusercontent.com/25764850/27351295-203a596a-55fd-11e7-91d6-fed6a887e7e7.JPG)

**Comment by kinappy** [comment]
It has actually returned char info this time but also added to queue and timeouts

**Comment by crumdidlyumshis** [comment]
If your on a warmane server, this is bound to. E your problem. Warmane porposly adds a timeout to the /who system for latency and server spam issues.

**Comment by kinappy** [comment]
Yeah I heard they have something in place, you can;t send a /who request straight after each other, you have to wait a while.

I disabled class caching and tried again so you can see the difference
![capture1](https://user-images.githubusercontent.com/25764850/27353710-643ebe32-5605-11e7-8618-e206db7b50c2.JPG)
![capture2](https://user-images.githubusercontent.com/25764850/27353711-643f81f0-5605-11e7-8278-e3f88d716c71.JPG)

**Comment by kinappy** [comment]
I have tried on a few other 2.4.3 servers and things are working fine with class caching enabled.

I guess this is something specific to Warmane and people should probably look at disabling class caching if they are bothered about /who

I'll close this as it looks like it's not a fault of the addon.

Regards
