### ISSUE TITLE
Datatext tooltips problem with Fubar2Broker

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#196]
Because of missing support of the most Ace2 addons for the datatexts I use Fubar2Broker (https://www.wowace.com/projects/fubar2broker/files/123370) for implementing Atlasloot, GatherMate, Headcount, ZOMGbuffs etc. to the Datatexts. Unfortunately the ZOMGbuffs tooltip doesn't show up after some minutes of raiding. Left/Rightclick does work but the tooltip which includes some interactions ((de-)activate buff checker and self buffs) won't show up. After a relog it works for some minutes again.
Sadly I got no error.

With my old interface and the Databroker addon "StatBlockCore" I hadn't these problems in combination with Fubar2Broker.

**Comment by Loaal** [comment]
It's known problem of Fubar2Broker.
Probably problem was solved after commit ff9be2b0b87f879df883b773fc79973bc06541a9
Please update ElvUI and report if it still happening.

**Comment by fatlus** [comment]
Seems good for me except the issue #219
