### ISSUE TITLE
3 left buttons of bar3 not clickable

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#198]
Sometimes in a raid the left 3 buttons are not clickable

**Comment by fatlus** [comment]
It happens a lot more in the last time

**Comment by Bunny67** [comment]
1 Enable !DebugTools (If not enabled)
2 Run command in chat /fstack
3 Move cursor to buttons
4 Screenshot

**Comment by fatlus** [comment]
Ok, problem found. There is a bonus actionbar which overlays bar3:

![wowscrnshot_062817_155703_2](https://user-images.githubusercontent.com/6052285/27640925-c32993ac-5c1a-11e7-9945-ef93464e628d.jpg)
![wowscrnshot_062817_155703_1](https://user-images.githubusercontent.com/6052285/27640932-c88bb154-5c1a-11e7-9236-3b929e39950e.jpg)

**Comment by crumdidlyumshis** [comment]
Fixed? Close?

**Comment by Larsy93** [comment]
Its fixed for me.

**Comment by fatlus** [comment]
Looks good
