### ISSUE TITLE
Sale prices inaccurate

### ISSUE THREAD

**Issue by kimnnmadsen** [ElvUI-TBC/ElvUI#199]
It seems sale prices are very inaccurate 
Examples:
Nightscape Headband - Actual: 44s 95c - ElvUI 4g94s95c
Rugged Leather: Actual 5s per each 1g for 20 - ElvUI 1g55s regardless of stack size
Thick Armor Kit: Actual 10s each 1g for 20 - ElvUI 1g70s regardless of stack size.
Freshly-Squeezed Lemonade Actual 2s each 40s for 20 - ElvUI 18s regardless of stack size.

**Comment by crumdidlyumshis** [comment]
This will be further looked into. The main issue is that blizzard introduced a function outside of merchants that display the price of the items as if you were next to a merchant. This however did not exist in TBC. A library was added that was created before wrath to gather prices. This bug may also depend on how accurate a server you play on has a correct DB in regards to item prices. 

Regardless, it is of importance, and will be looked into. Hopefully we can resolve this matter. Thank you for your report!

**Comment by crumdidlyumshis** [comment]
@Loaal @Bunny67 maybe take a look at http://www.wowinterface.com/downloads/info6518-VendorValues.html#info

Could help, not sure though.

**Comment by fatlus** [comment]
Also a problem with sell prices of stacks
![wowscrnshot_071217_170957](https://user-images.githubusercontent.com/6052285/28124894-3e51364c-6725-11e7-9c49-b90ae4117c67.jpg)

The price value should be 3g (5x 60s). Instead it shows the value for a single heal potion.

**Comment by crumdidlyumshis** [comment]
We have been talking about this issue and it's a hard one to solve but we are still brainstorming what we could do. Don't expect any fix for now. :)
