### ISSUE TITLE
.\AddOns\ElvUI\modules\chat\classCache.lua line 72:

### ISSUE THREAD

**Issue by tjukoela** [ElvUI-TBC/ElvUI#203]
Date: 2017-06-23 16:10:46
ID: 53
Error occured in: Global
Count: 31
Message: ..\AddOns\ElvUI\modules\chat\classCache.lua line 72:
   attempt to index field '?' (a nil value)
Debug:
   [C]: ?
   ElvUI\modules\chat\classCache.lua:72: GetClassByName()
   ElvUI\modules\chat\chat.lua:761: GetColoredName()
   ElvUI\modules\chat\chat.lua:795: ChatFrame_MessageEventHandler()
   ElvUI\modules\chat\chat.lua:978:
      ElvUI\modules\chat\chat.lua:971
AddOns:
  Compatibility, v1.0
  DebugTools, v1.0
  Ace, v1.4
  ACP, v2.4.3.$Revision: 79593 $
  Atlas, v1.12.0
  AtlasBattlegrounds, v1.12.0
  AtlasDungeonLocs, v1.12.0
  AtlasFlightPaths, v1.12.0
  AtlasOutdoorRaids, v1.12.0
  AtlasLoot, vAtlasLoot Enhanced v4.06.04
  AtlasLootBCInstances, v4.05.00
  AtlasLootCrafting, v4.06.00
  AtlasLootOldInstances, v4.05.00
  AtlasLootRepFactions, v4.05.00
  AtlasLootSetsandPvP, v4.05.00
  AtlasLootWorldLoot, v4.05.00
  AtlasQuest, vAtlasQuest 4.1.2
  AucAdvanced, v5.0.0
  AucFilterBasic, v5.0.0 (BillyGoat)
  AucScanData, v1.0
  AucStatClassic, v5.0.0 (BillyGoat)
  AucStatHistogram, v5.0.0 (BillyGoat)
  AucStatPurchased, v5.0.0 (BillyGoat)
  AucStatSimple, v5.0.0 (BillyGoat)
  AucStatStdDev, v5.0.0 (BillyGoat)
  Auctioneer, v5.0.0
  Bartender4, v4.0
  BeanCounter, v5.0.0 (BillyGoat)
  Carbonite, v1.4
  Cartographer, vr74405
  ClearFont2, v2.4
  CombatLogFix
  CooldownCount, v3.0
  FlightMap, v2.4-1
  eCastingBar
  Enchantrix, v5.0.0
  EnchantrixBarker, v5.0.0 (BillyGoat)
  EnhTooltip, v5.0.0
  EQCompare, v1.4
  FuBarMailFu, v2.0
  Informant, v5.0.0
  JIMCooldownPulse
  Ace2
  Ace3
  MikScrollingBattleText, v5.2.14
  MobInfo2, v3.61
  MoveAnything
  Postal, v2.1 r73730
  Postman, v2.0.53232
  Prat, v2.0 63303
  QuestReward, v1.2
  Recount, v901
  SellJunk, v55254
  Stubby, v93
  Swatter, v5.0.0
  TurnIn, v2.0.8
  VendorValues, v4.1.0
  ZHunterMod
  ElvUI, v1.32

**Comment by Loaal** [comment]
Under what circumstances was the error received?
