### ISSUE TITLE
Enemy nameplates with wrong colors

### ISSUE THREAD

**Issue by Redtuzk** [ElvUI-TBC/ElvUI#205]
Enemy nameplates will occasionally take on a wrong color, such as a friendly unit, passive (when mob is aggresive, or vice versa) or that of a random class.

Haven't noticed any errors, but this is what it looks like in game: http://i.imgur.com/g70WMDJ.jpg

**Comment by Larsy93** [comment]
What do you use for energybar/combopoints?

**Comment by Redtuzk** [comment]
@Larsy93 ElvUI's own, both detached from the player/targetframe.

**Comment by Larsy93** [comment]
huh how do you detach them?

**Comment by crumdidlyumshis** [comment]
Fixed? Close?

**Comment by Larsy93** [comment]
Its fixed for me.
