### ISSUE TITLE
Not showing druid HoTs (maybe other classes too) on raidframes

### ISSUE THREAD

**Issue by Maylus** [ElvUI-TBC/ElvUI#209]
I don't see any of my druid HoTs Lifebloom/Rejuvenation/Regrowth.
Only Debuffs top right.
How can i enable them in ElvUI for WoW 2.4.3? It's really important for all healers.
Thank you

**Comment by w9nder** [comment]
Yes, this is because the Filters arent done. You can create your own filters in the Filters tab under the configuration

**Comment by Redtuzk** [comment]
Aside from buffs, has anyone had any luck at all with getting the Buff Indicators to work?
They seem completely unresponsive to any change I make

**Comment by Maylus** [comment]
Thank you, but how can i create it?
I created new filter called My HoTs. Added my Lifebloom, Rejuvenation and Regrowth.
But it doesnt work. What i do wrong. I googled it but not found any information.
You guys are my last hope to get it working. Please help.

**Comment by Pziko** [comment]
@Maylus My friendly advice would be to use another unitframes since the default ones are a disaster.

**Comment by palenius** [comment]
Bump! Im having the same issue, real annoying how hard its tracking my renew. I added renew to filters and buff indicators but still they dont show on party/ raid unitrframes as the tiny box like they should (here's an example: http://imgur.com/a/RQ6Jj )
