### ISSUE TITLE
Nameplate bug

### ISSUE THREAD

**Issue by Dehcimal** [ElvUI-TBC/ElvUI#21]
It seems that , when you wanna change the options from the nameplates (such as showing health of the enemy both npc and real player) it does nothing even tho i did /rl.

**Comment by crumdidlyumshis** [comment]
Yeah the nameplates need some tweaking. I noticed a bunch of CVars and functions are of the wrong name.

**Comment by crumdidlyumshis** [comment]
fix https://github.com/ElvUI-TBC/ElvUI/commit/c40d41e10d24c7518f046f049100f6db6acff9a1
