### ISSUE TITLE
Professions window - Slight overlap

### ISSUE THREAD

**Issue by Redtuzk** [ElvUI-TBC/ElvUI#213]
The header of a given item in the professions page slightly overlaps the "Reagents"-text (needs to be moved down by 10-15 pixels)

![professions ui bug](http://i.imgur.com/YeB5Ih4.png)

**Comment by Nosnevets** [comment]
@Redtuzk Hey, would it be possible for you to Share your ElvUI profile?

**Comment by Redtuzk** [comment]
@Nosnevets Here you go: https://pastebin.com/raw/Sicne2jH

You'll need ElvUI, ElvUI_AddonSkins and ElvUI_CustomTweaks + Recount to make a more or less exact replica of my setup. Let me know if you need help with anything.

**Comment by Nosnevets** [comment]
@Redtuzk Thanks for sharing dude, Tt does look pretty neat and minimalistic which is what I was looking for.

Now, what about the Buff and Debuff indicator you have on this screenshot: http://i.imgur.com/g70WMDJ.jpg .

Thanks in advance.

**Comment by Redtuzk** [comment]
@Nosnevets Those are made with Modified Power Auras (google it). 
It's honestly a super shitty and buggy addon that does all sort of random crap, but it offers the most features comparing to WeakAuras that I'm used to from life.

**Comment by Nosnevets** [comment]
@Redtuzk I sort of thought it. I'm myself used to Weakauras2 over at Wotlk. Either way I appreciate the share :+1:
