### ISSUE TITLE
(Chat) Shift+Mouse left = ?

### ISSUE THREAD

**Issue by qvortx** [ElvUI-TBC/ElvUI#214]
Hello. Many thanks for the backport is wonderful. I want to report the problem of Shift + Mouse click on the name in the chat (for detailed info). This command does not work (or it is triggered a minute after pressing O_O

**Comment by Redtuzk** [comment]
Not a UI problem, if you're playing on Warmane it's because they restrict the /who function heavily.

**Comment by crumdidlyumshis** [comment]
As @Redtuzk mentioned, this sounds like an error due to a server. Warmane is notorious for adding this to their servers. Closing.
