### ISSUE TITLE
Micro stutter when buying an item

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#217]
Everytime I get an item in my bag, I receive a micro stutter. Doesn't know if it's the fault of my PC but before last commits this doesn't happened.

**Comment by crumdidlyumshis** [comment]
Fixed? Hah

**Comment by fatlus** [comment]
No, I thought this was my PC's fault. But after a restart it happens again. Do you have an idea or same problem?

**Comment by crumdidlyumshis** [comment]
Not aware of it since I haven't played much at all last couple weeks but we will look into it!

**Comment by crumdidlyumshis** [comment]
Maybe this could be related to b1e36d83dcad08fd08eabb8bdae71ed67de968b6?

**Comment by Larsy93** [comment]
Its fixed for me.

**Comment by fatlus** [comment]
Looks good
