### ISSUE TITLE
Item Glow Removal / Power Bar enlarger.

### ISSUE THREAD

**Issue by Gangsquadlolqtxyo** [ElvUI-TBC/ElvUI#218]
Hey lads. I didnt quite know what to call the topic but heres the thing, you know the glow a items get. i.e when the item is an epic the item icon in the bags or in the character dressing room gets a purple border/glow to it, how in the actual hell do I remove this cause its messing with my eye heavily. 

Would appreciate an answer and solution, thank you! 
Also under what tab can I find to increase the height of the Power (mana) bar? Can't seem to find it anywhere.

**Comment by crumdidlyumshis** [comment]
![wowscrnshot_070217_213617](https://user-images.githubusercontent.com/7307335/27776243-905cebe8-5f6e-11e7-9c0c-c7678a993974.jpg)

As for the item glow. Maybe an option is doable in ElvUI_Enhanced. @Loaal Maybe a toggle button under general to enable/disable the item border quality for character frame/bags/bank/guild bank?

**Comment by Gangsquadlolqtxyo** [comment]
hmmm @crumdidlyumshis where can I find this Enhanced thingie? Im kinda new to ElvUI firs ttime using it so im hella confused.

**Comment by crumdidlyumshis** [comment]
https://github.com/ElvUI-TBC/ElvUI_Enhanced

However, nothing is added for that feature to remove the border quality color. I fiddled with it last night and had some of the new option added but it needs a little more work. Maybe next couple days it will be added to ElvUI_Enhanced

**Comment by crumdidlyumshis** [comment]
Unfortunately, it is harder to add than expected. This cannot be done as I thought it could. So sorry. Closing for now.
