### ISSUE TITLE
Map can't be closed with Escape button

### ISSUE THREAD

**Issue by havlicekdom** [ElvUI-TBC/ElvUI#22]
When you open world map, it can be closed only with the open world map key binding ("M" by default). Escape key opens game menu instead.

Btw thanks for doing this, I found some problems with the UI, nothing game breaking tho. I will create issue for all of the stuff I found.

**Comment by crumdidlyumshis** [comment]
Thank you for your feedback! We enjoy doing what we do :) I will look into this shortly. Keep them issues coming!

**Comment by crumdidlyumshis** [comment]
https://github.com/ElvUI-TBC/ElvUI/commit/39ea72a65f53ac9176221ebc3b2116f40ac80fbd
