### ISSUE TITLE
[Feature Request] Aurabuff reminder selector

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#222]
It would be cool if the user has the control of the buffs which are displayed in the aurabuff reminder frame. For example every DD should have displayed Blessing of Salvation in this frame, a tank Blessing of Light/Sanctuary.

**Comment by crumdidlyumshis** [comment]
Maybe we could make a input section that allows you to add an array of ID's followed by commas? Instead of hardcoding them in but followed by defaulted ID's

**Comment by Apollyonn** [comment]
This is not going to be added. If you want i can add some extra buff icons for Tank, Caster and Dps.
