### ISSUE TITLE
Talent specialization not shown in tooltip

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#223]
The tooltip option "inspect information" should shown the talent specialization of a player and the Gearscore. The Gearscore isn't relevant in TBC but the talent specialization is possible (the Addon Cowtip has the ability).

**Comment by Loaal** [comment]
Information will be displayed only if you hold down the Shift key.
https://github.com/ElvUI-TBC/ElvUI/blob/master/ElvUI/modules/tooltip/tooltip.lua#L421
I'll update option desc later.

**Comment by fatlus** [comment]
Wonderful, doesn't know this option. Closed for me
