### ISSUE TITLE
Target Unit Frame text positions showing incorrectly

### ISSUE THREAD

**Issue by sifiuocz** [ElvUI-TBC/ElvUI#226]
Hello,
I've discovered weird behaviour of the unit frames. When targeting myself and other players, it shows everything correctly. But once i target anything else the texts seem to be showing incorrectly.
Just to be sure I deleted cache and WTF folders from my client and the problem still remains.

Hopefully you will understand better from these screenshots.
When i target myself:
![wowscrnshot_070417_163613](https://user-images.githubusercontent.com/13140968/27834717-55c417de-60d8-11e7-89f7-917cd15a0374.jpg)

When i target anything else:
![wowscrnshot_070417_163616](https://user-images.githubusercontent.com/13140968/27834720-5904e694-60d8-11e7-9810-1b0666291f29.jpg)

**Comment by Bunny67** [comment]
Uncheck Text Toggle On NPC

**Comment by sifiuocz** [comment]
Oh my god. I should buy new glasses. Thank you very much. The problem is solved.
