### ISSUE TITLE
Unitframes - Inset power isn't showing up

### ISSUE THREAD

**Issue by havlicekdom** [ElvUI-TBC/ElvUI#23]
When using "Inset" style and offset 0 for Power bar in UF (I tried Player, Target and Target of target), the bar disappears.

**Comment by crumdidlyumshis** [comment]
I think this is how it should work. Just drag the offset to begin seeing how far apart you want the distance between the two. I checked this on other versions of ElvUI and they seem to do the same exact thing. Closing for now.
