### ISSUE TITLE
ShapeShift Error

### ISSUE THREAD

**Issue by Hektek23** [ElvUI-TBC/ElvUI#231]
Message: ...ce\AddOns\ElvUI\modules\actionbars\barShapeShift.lua:50: GetSpellInfo(): Invalid spell slot
Time: 07/06/17 18:14:50
Count: 2
Stack: (tail call): ?
(tail call): ?
[C]: ?
...ce\AddOns\ElvUI\modules\actionbars\barShapeShift.lua:50: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Loaal** [comment]
What class did you play, when this error occur?

**Comment by crumdidlyumshis** [comment]
Actually I think I had this same error once before. I was on smolderforge server in storm wind on a Palidan with crusader aura. I talked to the server npc to teleport to the player mall. This is when I received that message.

**Comment by Hektek23** [comment]
i played Druid.
