### ISSUE TITLE
Tooltip font settings default after reload

### ISSUE THREAD

**Issue by Redtuzk** [ElvUI-TBC/ElvUI#232]
Fontflag set, pre-reload:
![.](http://i.imgur.com/5cxvgWK.png)

After reloading:
![.](http://i.imgur.com/vZWZopR.png)
Healthtext seems unaffected.
Not getting any LUA errors.

**Comment by crumdidlyumshis** [comment]
Hmm, trying to understand what you are trying to accomplish. On my screen, both those images seem the same, but im having trouble understanding what you have checked or toggled.

**Comment by Redtuzk** [comment]
@crumdidlyumshis Alright, yea sorry it could've been a little more clear. You have to look really closely to notice the difference, but the top picture has the outline, bottom one doesn't.

So basically the font outline option for tooltips doesn't seem to be working (found under /ec > Tooltips > Tooltip Font Settings. It works the first time you set it, but as soon as you reload the change is undone despite the setting looking enabled.

**Comment by crumdidlyumshis** [comment]
Ahh I see now what you're saying. I just tried it myself. Confirmed. ^^

**Comment by crumdidlyumshis** [comment]
Its actually all the general tooltip settings are reset after reload.
