### ISSUE TITLE
Filter not char based

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#234]
The ElvUI config is sepererated for every character. But the filter settings are account based

**Comment by Loaal** [comment]
It works as intended and not will be changed afaik.
The last word will be for @Bunny67

**Comment by fatlus** [comment]
So, what is the solution for the following case:
- 2 Chars on a account, one physical DD, one Caster
- I set up the filter for the physical DD that I only see melee debuffs on a enemy target (Sunder armor, fearie fire, Curse of Recklessness, Judgement oft the Crusader) to check if some necessary debuffs are missing.
- I log into the caster DD on the same account and now i want to see only caster debuffs (Curse of Elements, Judgement of Wisdom, Scorch, etc.). Instead of it, ElvUI copied the filter settings of the physical DD and shows me configured melee debuffs. In this case I must always set up all the filter settings manually before raiding
