### ISSUE TITLE
Cooldown problem on action bars

### ISSUE THREAD

**Issue by CptPoireau** [ElvUI-TBC/ElvUI#236]
Hello,

It doesn't show any error but my cooldown on action bars of Consecration isn't working.

As you can see on the screenshot i just casted it. Other skills are working fine.

https://i.imgur.com/URgbOCa.jpg

**Comment by fatlus** [comment]
Was fixed with https://github.com/ElvUI-TBC/ElvUI/commit/1351308213fa3363bdd347525536c8061f672735

**Comment by Bunny67** [comment]
Is the problem still there?

**Comment by crumdidlyumshis** [comment]
Works as intended. Closing.
