### ISSUE TITLE
[AuraBuffReminder] Buff duration text behind cooldown animation

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#237]
The text is nearly unreadable because he is not the top layer and is set behind the cooldown animation:

![wowscrnshot_071017_144125](https://user-images.githubusercontent.com/6052285/28018712-9f3257be-657e-11e7-846d-caa8de0a770e.jpg)

**Comment by Tremolo4** [comment]
"nearly unreadable"? You should get a monitor with better contrasts ^^

**Comment by fatlus** [comment]
The cooldown spiral and text is completly missing now

**Comment by Apollyonn** [comment]
![wowscrnshot_072117_100519](https://user-images.githubusercontent.com/19589902/28452628-35ce4d88-6dfc-11e7-8112-3f44eddc0bdc.jpg)
![wowscrnshot_072117_100525](https://user-images.githubusercontent.com/19589902/28452631-385c4f28-6dfc-11e7-847e-a176f7f7555f.jpg)

Seems fine to me

**Comment by fatlus** [comment]
Yes, was sort of a refresh bug with old buffs. New buffs are working flawless! Thank you!
