### ISSUE TITLE
Disable MobHealth

### ISSUE THREAD

**Issue by edizmetin** [ElvUI-TBC/ElvUI#240]
I don't use Elv-Uis player and target frames but MobHealth is still enabled. How can I disable or change health color/ font?

**Comment by Loaal** [comment]
MobHealth uses not only for UF, but also for Nameplates and Tooltip (HP texts). I didn't understand which frame you want to disconnect.

**Comment by edizmetin** [comment]
Player and target frame

**Comment by Loaal** [comment]
![image](https://user-images.githubusercontent.com/590348/28063843-33551a28-663b-11e7-9b64-13f3ebb32ca0.png)
![image](https://user-images.githubusercontent.com/590348/28063901-661cea62-663b-11e7-999b-9a6422a600fe.png)

**Comment by edizmetin** [comment]
I know about those settings, but as I said above I do not use Elv UI default Unitframes, but Blizzard ones instead. Even though Elv UIs untiframes are disabled I still get mobinfo HP numbers.

**Comment by Loaal** [comment]
![image](https://user-images.githubusercontent.com/590348/28093861-0b530500-66a2-11e7-813e-5baf7a30ebfa.png)
![image](https://user-images.githubusercontent.com/590348/28093822-d09afb2a-66a1-11e7-8e3f-de89ed515287.png)
On my side all works fine.

**Comment by edizmetin** [comment]
Even though font isn't default one still works, thank you! Probably should open a new issue but is it possible to see debuffs on enemy nameplates?

**Comment by Loaal** [comment]
![image](https://user-images.githubusercontent.com/590348/28223699-1b3d5d46-68d5-11e7-95b4-42093796d5ed.png)
Issue about nameplate buffs/debuffs already exists
