### ISSUE TITLE
Castbar dissapears instead of increasing cast duration when getting a hit

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#243]
It occuresf or example in the Naj'entus fight in Black Temple when you getting the AoE dmg effects. The castbar disappears instead of getting a cast duration increase (the cast itself works). It was a known problem with Quartz on my server where I play (Back2Basics) and a user wrote a fix for it. He changed something in the Player.lua of Quartz (code: https://pastebin.com/BCNs5f0i).

Here a possible bug description:
"The error is probably due to the fact that the addons start a query to check the original cast time, then how the new cast time is when there was an "interruption" or "delay". In addition other "casts" are incorrectly prompted. For the Mage eg. ice shield.
If I cast as a mage and have the ice shield on me, the whole thing works so long until a mob hits me, because the ice shield was triggered and the addon thinks "finished" with the cast of the started spell ,"

**Comment by Apollyonn** [comment]
I'm unable to reproduce it. Here is an example of a hunter channeling a spell and a warlock using hellfire as an AOE spell. The casting time reduce each time the hunter takes dmg and it works as it should.
![ezgif com-crop](https://user-images.githubusercontent.com/19589902/43551082-629f4914-95ee-11e8-904f-b1f7d63e5f56.gif)
![ezgif com-crop2](https://user-images.githubusercontent.com/19589902/43551209-e6e89bbc-95ee-11e8-9d88-036c2e1da92b.gif)
