### ISSUE TITLE
Text behind recount [Graphical issue]

### ISSUE THREAD

**Issue by TIGJERUX** [ElvUI-TBC/ElvUI#247]
https://gyazo.com/69f418ce8f265a674b92976b76869309
Theres like 1-2 pixels of text behind the recount, you could move recount up by like 1 pixel or something to hide it. <3

**Comment by crumdidlyumshis** [comment]
![wowscrnshot_071317_195059](https://user-images.githubusercontent.com/7307335/28193742-a95366ec-6804-11e7-8e01-b563fe9aa0d1.jpg)

**Comment by TIGJERUX** [comment]
that completely gets rid of Loot / Trade for me
https://gyazo.com/63c9bdd6e1fc29f197e995c1256e18fe

**Comment by crumdidlyumshis** [comment]
When recount disappears it should show loot/trade again does it not? It seems to work on my side.

**Comment by TIGJERUX** [comment]
It might be on my side then, 
This is what I get.
https://gyazo.com/582fb33fdf7327edec4f112f8fac77d5
It stays like this for like 30 secs, then Loot / Trade overlays with recount.
https://gyazo.com/582fb33fdf7327edec4f112f8fac77d5
https://gyazo.com/7d293b72380b1eb5d449e9f3bbd1249e
After I click like this for like 1 minute and get the Loot / Trade to show up its empty untill i https://gyazo.com/baeb47c05f056b0d68fcd3847bb88bd9

I hope theese screenshots arent confusing. :D
I am using no chat addons. or anything like that

**Comment by TIGJERUX** [comment]
Disabled every addon but elvui and recount, same thing happens.

**Comment by crumdidlyumshis** [comment]
Actually it has to do with PositionChat function in ElvUI, which is something @Loaal and I have discussed. I honestly do not know how to fix this, but maybe a fix will be applied shortly. I have noticed this too.
