### ISSUE TITLE
Chat Lua Error

### ISSUE THREAD

**Issue by Tristan000** [ElvUI-TBC/ElvUI#249]
Message: Interface\AddOns\ElvUI\modules\chat\chat.lua:949: bad argument #3 to 'format' (string expected, got no value)
Time: 07/12/17 22:19:11
Count: 1
Stack: [C]: ?
[C]: ?
Interface\AddOns\ElvUI\modules\chat\chat.lua:949: in function `ChatFrame_MessageEventHandler'
Interface\AddOns\ElvUI\modules\chat\chat.lua:998: in function `ChatFrame_OnEvent'
Interface\AddOns\ElvUI\modules\chat\chat.lua:1004: in function <Interface\AddOns\ElvUI\modules\chat\chat.lua:1003>

**Comment by crumdidlyumshis** [comment]
I just confirmed this error.
I soloed Deadmines as a 70 palidan, walked out the back exit and immediately recieved this error.

`Message: Interface\AddOns\ElvUI\modules\chat\chat.lua:949: bad argument #3 to 'format' (string expected, got no value)
Time: 07/13/17 22:03:28
Count: 62
Stack: [C]: ?
[C]: ?
Interface\AddOns\ElvUI\modules\chat\chat.lua:949: in function `ChatFrame_MessageEventHandler'
Interface\AddOns\ElvUI\modules\chat\chat.lua:998: in function `ChatFrame_OnEvent'
Interface\AddOns\ElvUI\modules\chat\chat.lua:1004: in function <Interface\AddOns\ElvUI\modules\chat\chat.lua:1003>`
