### ISSUE TITLE
Unitframe Error

### ISSUE THREAD

**Issue by Hektek23** [ElvUI-TBC/ElvUI#250]
Message: ...rface\AddOns\ElvUI\modules\unitframes\unitframes.lua:714: attempt to call upvalue 'GetInstanceInfo' (a nil value)
Time: 07/12/17 22:11:09
Count: 4
Stack: (tail call): ?
(tail call): ?
...rface\AddOns\ElvUI\modules\unitframes\unitframes.lua:714: in function `CreateAndUpdateHeaderGroup'
...rface\AddOns\ElvUI\modules\unitframes\unitframes.lua:931: in function `UpdateAllHeaders'
...rface\AddOns\ElvUI\modules\unitframes\unitframes.lua:1035: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

it happens when i enter a instance (SSH) or get ressed

**Comment by Loaal** [comment]
Make sure you use latest version of ElvUI, and all addons which goes with it.
