### ISSUE TITLE
Enemy cast bar doesn't stop after interrupt

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#251]
As you can see on the screen i kicked a spell successfully but the cast bar animation still continues.
![wowscrnshot_071317_125801](https://user-images.githubusercontent.com/6052285/28163404-3ffa96f4-67cb-11e7-8af3-49b5caea7d3a.jpg)

**Comment by Loaal** [comment]
Can't reproduce.

**Comment by Redtuzk** [comment]
Getting the same thing, seems inconsistent though.

**Comment by qvortx** [comment]
same thing

**Comment by Tr1n1ty1** [comment]
Happens with Quartz aswell albeit very rarely, maybe Client related?
Seems to happen way more often with ElvUI tho

**Comment by qvortx** [comment]
I decided to put back the old version and everything fell into place

**Comment by fatlus** [comment]
No chance to get it fixed?

**Comment by Apollyonn** [comment]
Check now please

**Comment by fatlus** [comment]
Looks good for me!
