### ISSUE TITLE
Change floating combat text?

### ISSUE THREAD

**Issue by HuMa69** [ElvUI-TBC/ElvUI#255]
The setting on "media" for combat text doesnt change the floating numbers above the characters and moobs when you attack them, how can i change it? im looking on the lua files but i dont see anything

**Comment by crumdidlyumshis** [comment]
![wowscrnshot_071417_220540](https://user-images.githubusercontent.com/7307335/28236028-c4309f2a-68e0-11e7-845f-eebf77b712c7.jpg)

**Comment by crumdidlyumshis** [comment]
![wowscrnshot_071417_230517](https://user-images.githubusercontent.com/7307335/28236323-10e9247e-68e9-11e7-9c7f-4887effc6192.jpg)

**Comment by HuMa69** [comment]
can you read my message man? that optione dosnt change the floating damage numbers, just the letters like LEAVING COMBAT etc

**Comment by crumdidlyumshis** [comment]
Unfortunately I cannot reproduce as it is fully working on my side.
