### ISSUE TITLE
Health Deficit

### ISSUE THREAD

**Issue by Crusader9x** [ElvUI-TBC/ElvUI#256]
Hey, 
I was trying to get health deficit to show on my player frame.  Basically if i had just deficit to show it worked fine.  Although when I tried to get it to display with current/max/percent it didnt work.  It would jsut display what I typed.  I can get current and or max and or percent to work just fine but when try to use one or all with deficit it doesnt work. 

Basically I would like to be able to see max current deficit, or something to that effect.

Thanks for your time and effort so far in this.

**Comment by Apollyonn** [comment]
Try this [health:current-max-percent]

**Comment by Crusader9x** [comment]
That works just fine.  I would really like to be able to put deficit in there instead of percent.  Or something else with deficit if not those two.

**Comment by Apollyonn** [comment]
You can add a second tag if you want, for example **[health:current-max] [health:deficit]**

**Comment by Crusader9x** [comment]
Thanks.  That is exactly what I was looking for.
