### ISSUE TITLE
Sticky Chat dont work with Custom Channel

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#257]
Normaly should the Sticky Chat option work with every channel, even with custom channel you create, but for those custom channel and officer chat it doesn't work, it just work with standard channel like /guild, /party, /raid etc.

**Comment by lishpeth** [comment]
I can confirm this. Sticky chat option only works for guild/party etc default channels right now...

**Comment by fatlus** [comment]
Now the /w is always sticky. There should be an exception for this specific channel
