### ISSUE TITLE
LibRockConfig Error

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#259]
It happens when i click on Cartographer addon Button, without ElvUI it worked as it should.

[2017/07/13 02:38:20-20-x1]: LibRockConfig-1.0-5058:762: attempt to index field 'titleText' (a nil value)
LibRockConfig-1.0-5058:7297: in function <...grapher\libs\LibRockConfig-1.0\LibRockConfig-1.0.lua:7290>

**Comment by Loaal** [comment]
Can't reproduce. Please try to disable all addons exclude Cartographer, ElvUI, ElvUI_Config and check if error still appears. Also need version number of Cartographer.

**Comment by fatlus** [comment]
Can't approve it. Was a forwarded issue of another member on my server
