### ISSUE TITLE
ElvUI breaks Cartographer3

### ISSUE THREAD

**Issue by Tremolo4** [ElvUI-TBC/ElvUI#261]
When hovering over a zone with the mouse in Cartographer3, large black textures that look like the ElvUI skin appear. While not having the mouse inside the Map window, the black textures appear over the current zone.

Seems to be related to map icons, like the House for flight points/towns or ElvUI "coordinates" (which I'm not using).

I'm using this version, which is the latest "Release" for 2.4.3: https://www.wowace.com/projects/cartographer3/files/86442

Screenshot: https://dbr.ee/VMaa

**Comment by Loaal** [comment]
You need to disable World Map skin. Also you can use [ElvUI_AddonSkins](https://github.com/ElvUI-TBC/ElvUI_AddOnSkins)

**Comment by Tremolo4** [comment]
Thanks!
