### ISSUE TITLE
Buffs being picked up as debuffs

### ISSUE THREAD

**Issue by Redtuzk** [ElvUI-TBC/ElvUI#263]
As you can see on the screenshot, some of my buffs are being picked up as debuffs (above player frame) in this case Water Walking, Lightning Speed (mongoose's proc) and my trinket's on-use. 

This has been happening for a couple of days, so it came with a recent commit.

![.](http://i.imgur.com/lnb5lsQ.jpg)

**Comment by Bunny67** [comment]
I do not see the debuffs :(

**Comment by Redtuzk** [comment]
Right above my unitframe, that's the whole thing: Auras that are buffs (on me) are being picked up as debuffs (above the player frame) :)

**Comment by Apollyonn** [comment]
![wowscrnshot_072117_183109](https://user-images.githubusercontent.com/19589902/28470600-dfcdd560-6e42-11e7-8817-9aca6e0e89ac.jpg)
check this option, maybe you have TOPLEFT both buffs and debuffs

**Comment by Redtuzk** [comment]
Don't have have buffs enabled, but I'll try 👍

**Comment by Redtuzk** [comment]
Tried the changed you suggested @Apollyonn - same result :(

**Comment by Bunny67** [comment]
I could not reproduce

**Comment by Redtuzk** [comment]
@Bunny67 Nor can I, consistently anyways. It happens at random, and it's happening for several of my guildies too after they updated a couple of days back. I'll keep an eye out for errors and report back.

**Comment by mpuryear** [comment]
I'm fairly certain this is a problem with either the client or server, on warmane's servers even with default buff frames I often see buffs as debuffs after any sort of loss of control.

**Comment by pzilou** [comment]
got the same issues, sometimes there is
["attachTo"] = "DEBUFFS",
in savedvariables, but not everytime, not sure thats the problem

**Comment by TIGJERUX** [comment]
It might be server sided, because on warmane atm same thing happens for Decursive, Grid, yada yada, randomly picks up Prayer of Mending as debuff same thing with Renew.

**Comment by pzilou** [comment]
yes but only happens if you have elvuitbc, grid alone no problem

**Comment by Redtuzk** [comment]
Think we've more or less concluded that this is a serverside issue with Warmane, so closing ticket again
