### ISSUE TITLE
1-2 buttons on Bar4 aren't working.

### ISSUE THREAD

**Issue by TIGJERUX** [ElvUI-TBC/ElvUI#264]
https://gyazo.com/a9a4d7a7a973bc20331895612a59a748

When hovering over button 6 it picks up as if theres nothing there. Even if I disable mouseover for bars can't click that button or use it.

**Comment by Bunny67** [comment]
https://gyazo.com/e3ce3dec6635b6610d0220fca98f9c81

**Comment by TIGJERUX** [comment]
Idk now its fixed lol
