### ISSUE TITLE
cant use search function

### ISSUE THREAD

**Issue by sckush** [ElvUI-TBC/ElvUI#265]
there have a issues is cant search somebody and u cant use search find who u want

pls fix it
best regard

**Comment by crumdidlyumshis** [comment]
Can you provide more information as to what search your talking about and any errors or steps to provide what you did? Maybe list addons?

**Comment by fatlus** [comment]
I think he means the ingame search function via /who player/guild

**Comment by sckush** [comment]
@fatlus yep as u say

**Comment by sckush** [comment]
who list u cant search anything it will give u aways "please wait"

**Comment by Loaal** [comment]
You can disable class caching feature by unchecking "Class Caching".
![image](https://user-images.githubusercontent.com/590348/28522415-9cd6c24a-7080-11e7-9fb6-eed89a815456.png)

**Comment by sckush** [comment]
@Loaal thanks , little work, but cant search one player name , only show 50 people

**Comment by Loaal** [comment]
I'm not sure that you mean, can you describe how to reproduce it?
![image](https://user-images.githubusercontent.com/590348/28522833-4c216f06-7082-11e7-9fb6-b2574a66c480.png)

**Comment by sckush** [comment]
@Loaal can work but should wait too many time

**Comment by fatlus** [comment]
Generally this is a problem on private servers not the major problem of ElvUI. On my server (Back2Basics) you cannot search for player levels, guild names/locations with blanks or classes (like /who rogue 70 which works on retail). The only issue with ElvUI I had noticed is that the search is a little bit slow. Sometimes it requires some seconds until the search result is shown in the chat. This problem is gone when I deactivate ElvUI. But I also read that other servers like Warmane have search limitations for controlling flooding.

**Comment by Loaal** [comment]
Not sure it's our bug, without ElvUI **/who** works fine?
**/who** function may be limited on server side.

**Comment by sckush** [comment]
![image](https://user-images.githubusercontent.com/25095351/28523226-fefa3d80-70ad-11e7-8ca6-74bc3e78a5ce.png)

![image](https://user-images.githubusercontent.com/25095351/28523374-aff73df4-70ae-11e7-96bd-94b5983d8d34.png)
i use addons can search who  like this pic

**Comment by Apollyonn** [comment]
Like fatlus said, some servers put a limit on the /who function for various reasons, if you are playing on warmane then its 100% server side.

**Comment by sckush** [comment]
and i have other suggest, the nameplate overlap can work .  shaguplate work it in vanilla, i think tbc also can work.
link: https://github.com/shagu/ShaguPlates

**Comment by Apollyonn** [comment]
maybe in the future.

**Comment by Bunny67** [comment]
@sckush Your offer can not be implemented in tbc

**Comment by lishpeth** [comment]
I have found a solution for people who is playing on Warmane. 

**Download -->** https://www.wowace.com/projects/wholib/files/308802?sort=game-version  Wholib Prewotlk version. Keep LibWho 2.0 in your Elvui library and extract this 1.0 pre wotlk version with its libraries into Elvui/Libraries folder. With this solution, there will be no waiting time (except the server's /who command cd). There will be no queue/timeout etc...

![wowscrnshot_081217_114407](https://user-images.githubusercontent.com/28478416/29239276-a4fdb9ba-7f53-11e7-948a-7befe33ba14c.jpg)
