### ISSUE TITLE
/who command is not working

### ISSUE THREAD

**Issue by lishpeth** [ElvUI-TBC/ElvUI#273]
I have tried to use /who command with shift-clicking the names in chat, I also tried to use "who" section for searching people in the game but these don't seem working properly and it seems shift-clicking to name in chat is not working at all. When I try to use the /who -name- command, it takes my command to a queue and then without showing, it says timeout --retrying... When I use the "who" window, it says -please wait- there. I have changed from a custom UI to ElvUI yesterday and there was no such thing. I could use shift-clicking on names and /who commans without a queue or retrying (except the server's 3 mins queue)... So I thought this might be because of ElvUI... 
Also it adds z- and n- letters to the searchs, this may cause the problem. While searching for people, it sometimes found the wrong persons also. As I have said I had no such problem till I switched to Elvui.
I was using custom addons like ShadowedUF/Kgpanels etc...

![wowscrnshot_072817_144340](https://user-images.githubusercontent.com/28478416/28715973-6b0a812c-73a3-11e7-932b-f925928baef9.jpg)

![wowscrnshot_072817_143352](https://user-images.githubusercontent.com/28478416/28715704-e5b12914-73a1-11e7-8b25-5fe0ea97c7b1.jpg)

**Comment by Loaal** [comment]
[Solution](https://github.com/ElvUI-TBC/ElvUI/issues/265#issuecomment-317400389)

**Comment by lishpeth** [comment]
Yes but then people with not be colored in chat. With Chatter addon, I had class coloring in chat and also a working /who command. Maybe something can be done about it with Elvui, too?

**Comment by Loaal** [comment]
You can change server, because it server-side problem.

**Comment by lishpeth** [comment]
I guess its not. I am playing on Warmane, with chatter (class colored DB cache) I had no problem. So I thought it may be Elvui. Because with even disabling the Class Caching, it queues the searchs when the search is on cooldown...
