### ISSUE TITLE
Random red bar appearing

### ISSUE THREAD

**Issue by jonomurphy** [ElvUI-TBC/ElvUI#274]
http://imgur.com/vF68j7A

Anyone know what that is?! Next to player unitframe!

**Comment by fatlus** [comment]
Is this ElvUI??? Looks terrible imho. The unitframes look like Pitbull, is it possible that you have this addon enabled?

**Comment by Tremolo4** [comment]
can confirm red bar with plain ElvUI

**Comment by Apollyonn** [comment]
fixed with https://github.com/ElvUI-TBC/ElvUI_Enhanced/commit/334189e33296276d631b1b9cc5c12d0bc30253f8

**Comment by Tremolo4** [comment]
Still happens for me. Reproducible when getting in combat while AFK. On my server the AFK flag is not removed automatically, which results in ElvUI instantly entering camera-spin-mode when combat ends. When camera-spin-mode, the red bar appears.
