### ISSUE TITLE
LUA Error in oUF RaidDebuffs

### ISSUE THREAD

**Issue by Tremolo4** [ElvUI-TBC/ElvUI#276]
Since the latest spell filter fixes from Bunny, I'm getting errors during combat with Mobs that apply Debuffs to my raid. (Not every fight, maybe 50%)
I don't have a log at the moment, will post as soon as I have one.

**Comment by Pziko** [comment]
It happens specially in pvp combats. Really annoying.

**Comment by Loaal** [comment]
Error log or it didn't happen

**Comment by Tremolo4** [comment]
soon™

**Comment by Tremolo4** [comment]
This error occured for my paladin after stunning a group member once during a duel.
From what I remember it's the exact same error as during the raid (also my paladin)

`Message: Interface\AddOns\!Compatibility\api\wowAPI.lua:63: Usage: UnitAura("unit", index [, filter])
Time: 07/31/17 22:32:02
Count: 320
Stack: [C]: ?
[C]: ?
Interface\AddOns\!Compatibility\api\wowAPI.lua:63: in function <Interface\AddOns\!Compatibility\api\wowAPI.lua:62>
...ries\oUF_Plugins\oUF_RaidDebuffs\oUF_RaidDebuffs.lua:114: in function <...ries\oUF_Plugins\oUF_RaidDebuffs\oUF_RaidDebuffs.lua:111>
`

**Comment by Tremolo4** [comment]
Same error after this commit. For both of my testing characters.

**Comment by lishpeth** [comment]
Raid frames now dont show more than 5 people right now with this fix.
