### ISSUE TITLE
Raid/Party Frames disappared all together

### ISSUE THREAD

**Issue by lishpeth** [ElvUI-TBC/ElvUI#279]
After the latest fix, raid/party frames are not showing anymore.

![wowscrnshot_080117_152401](https://user-images.githubusercontent.com/28478416/28825233-08440526-76ce-11e7-811c-33a901e7a190.jpg)

Here; you can see there are not anchors for raid/party frames.

![wowscrnshot_080117_152411](https://user-images.githubusercontent.com/28478416/28825266-2fea51ca-76ce-11e7-82cd-9f392c25ec61.jpg)

![wowscrnshot_080117_152432](https://user-images.githubusercontent.com/28478416/28825278-3fcf0734-76ce-11e7-8a08-25aebe2b2d78.jpg)

![wowscrnshot_080117_152506](https://user-images.githubusercontent.com/28478416/28825285-4b20d6ee-76ce-11e7-8ba6-65b075ee30b1.jpg)

**Comment by Loaal** [comment]
Please disable all addons exclude ElvUI and ElvUI_Config, and report if error still appears.

**Comment by lishpeth** [comment]
I have disabled them all except swatter.
 Here is the error;
Date: 2017-08-01 16:06:40
ID: 53
Error occured in: Global
Count: 1
Message: ...e\AddOns\ElvUI\modules\unitframes\elements\range.lua line 119:
   attempt to index field '?' (a nil value)
Debug:
   [C]: ?
   ...e\AddOns\ElvUI\modules\unitframes\elements\range.lua:119:
      ...e\AddOns\ElvUI\modules\unitframes\elements\range.lua:114
   ...e\AddOns\ElvUI\modules\unitframes\elements\range.lua:170:
      ...e\AddOns\ElvUI\modules\unitframes\elements\range.lua:157
   (tail call): ?
   ...erface\AddOns\ElvUI\Libraries\oUF\elements\range.lua:94:
      ...erface\AddOns\ElvUI\Libraries\oUF\elements\range.lua:88
AddOns:
  Compatibility, v1.0
  DebugTools, v1.0
  Swatter, v5.0.0
  ElvUI, v1.32

**Comment by Bunny67** [comment]
Delete the folders `!Compatibility, !DebugTools, ElvUI and ElvUI_Config` and try to add the addon again

**Comment by lishpeth** [comment]
I am using an older version Elvui right now (The one I downloaded yesterday for weakened soul buff indicator fix). This one I have linked the errors is a fresh one. I have downloaded it as fresh with deleting the folders you mentioned. I have tried four times, deleted the folders and download from the fresh zip file. The issue appeared after the fix with [https://github.com/ElvUI-TBC/ElvUI/commit/883757fbdd0ad12376b1c63a47616ad5b354873c](url)  

There was a mention here https://github.com/ElvUI-TBC/ElvUI/issues/276 for a lua error. And after the fix, first raid frames didnt appear more than 5 people in raid and then they totally dissappeared.

**Comment by lishpeth** [comment]
I have also deleted my lua files in Wtf and account. I have started the game, logged in, party/raid frames were there. Then I have imported my settings which I have exported before. And again party/raid frames dissapeared with the same error above...

**Comment by Bunny67** [comment]
share you settings

**Comment by lishpeth** [comment]
A0X0IQAgSCSXJCrNIrgFqXZBon5JVNQwVTqmpGWQ9IxI00jVNZWyTUV9U9A4leocpKwjFXVQqVhI1EOJMpFUuEjFRlV8pBIjSaWTCM1U4KZKdpLyE2KohKVU6ilqKugqor6SioyFROosJGKtREXeSlR1V6LKXvEXQYOVKoeBxYQeKzRZictSm6nyWSKjqeq0pNdU0mxFtxHZTfIbaTgRxyUqLId6rqrplOsqbFfKdxUZDwnnEVivVLVfqXTWwHArH6ixH1xbLX9QvwWGZ289y+ikOHKYet6sqge99Syjk+LI4VY+UGMv5URVRw5Tz5tVNfv0VE5UdeQw9bxZVTvKB2rsRQOkjhwLjwfGrQweRnEFMxpquNSqMZiBYfNxAwsMW6MwrvsdbV1jYRGMrgumkpFOigPDOM9dPxxKz/r31evPqOu6xkO/DcOlPHf9cCg9699Xrz+jrusaD/02DIt57vrhUHrWv69ef0Zd1zUe+m0YCxuVFED1jBgGnmvEMDiMulsCKg4Xgx2UOO4wqapKApLA8KQjsEoVbBQWZl1Ep7B4mFH1A8NgSnwQ7Q1X9evSV1WVBCSBYQn91SpVYYgUbqKLLoyFSfT4TbfGkcMSWpWFIVK4iS66MBaedARWqXqoMq77HW1dw3Wk6geGRzBbLQAHhv8IZkd7UR7eYrHwr/sdbb3dY2GR4qXxSCfFgWEx2hsuRXvDONobC4vUjJIKoHpGDItgdF0wlXhg6ZFOigPDINoaxnmGUv3w1d/vr/R+Hq7nNR76bRgu5RlK9cNXf7+/0vt5uJ7XeOi3YVjMM5Tqh6/+fn+l9/NwPa/x0G/DWHgD8+iRTooDw2K0F2U0tHAp2osyGloYR3tRRkOLhbdWC8UuGBD8yOFxgv/LwOi3u8tx9Dei8mjkWLiVD9TYS2B40t/UG6kyTGdg2E2pRQ7rqB9gUsQwK4A7Yiw8+sACw4vkD6py/ZFj4QUYsEZhPzBsldRldFLsqNGPHAuPPsBgtMaBYckEBI0DwxQvjTVA6vAqoAo34SxIBb0wjIWr+pIeTQajawnTQy2RwyIYXUuYHmqJHJa0yWB0LWF6qCVyLKwAqSUTWP/A8CdRan7kWBiMVqkSAf6BYcNAfQnArWxntEqVCPAPDBsG6ksAbmUyGF0XTCU/YiwWC4NlQRS7VvUDw00SewkM41ryLYyQWoVnexZ290gPZeEmib1AAkmHmai5DJxYLOzXpeFhFFcwo63hCQjoYdwW9hvMxuHRBxYYHo9vlAQrqcvopDgwLOa5o0rf9R3ebnqpdEU73+Kh36ThUp47qvRd3+HtppdKV7TzLR76TRrGee6o0nd9h7ebXipd0c63eOg3aSwsAaqnbteSb9HWuz5sldRsgCR5KCYBC5erq3O51+5eWAJUTwhEGYyuC6aSyGED4kOVcd3vaOsalgDVU6e6mB9NKr3HwkAkBYYN4FJb5LBkAoLGkWNhEt0a/8CwMzfyQ/jQ8fhl4JsI8EW3xmEZgRC5Bs4DBWduZGIBcCsTZARC5Bo4DxSk96GwrmvYmRv5ISwmIGhcBr6JAF90axyWEQiRS3DmRiYWALcyQUYgRC7hFYb3sDM38kPoBnW56NY4DJFi4DxQcOZGJhYAtzJBRiBEroHzQGF9b6+gP6OFB+1ZmQ/solvjsIxAiFwD54GCMzcysQC4lQkyAiFyDZwHClJBH3bmRn4I3aAukraLbo3DECkGzgMFZ25kYgFwKxNkBELkGjgPFPTCUHoO7xwY/ItujcMQKdxEF10oOHMjEwuAW5kAkcJNdNGFAvp6RhPQb2FnbuSHEAJcats5MLjo1jgsIxAil5voogsFZ25kYgFwKxNkBELkchNddKGArl/Pwor2hq86YioCfNGtcRgihZvoogsFZ25kYgFwKxMgUriJLrpQQNcL6Ov9HnbmRn4Ii7Yy8E0E+KJb47CMQIhcA+eBgjM3MrEAuJUJMgIhcg2cBwqo711Y0fRhZ27khxACXGqDAJfaLro1DssIhMglOHMjEwuAW5kgIxAil4B2F9b3HnbmJgNMWLSFZQRC5Bo4DxScuZGJBcCtTJARCJFr4DxQ0AuoaGt4QP8vo8ownRfdGochUgjO3MjEAuBWJkCkEF4BXTpECztzIz+EblAX/XvRrXEYIsXAeaDgzI1MLABuZYKMQIhcA+eBwvreXkE/RA07c9uRCdewjECIXIIzNzKxALiVCTICIXIJryC9h5257ciEqGEZgRC5BGduZGIBcCsTZARC5BJeQR925rYjE+rDMgIhcrmJLrpQcOZGJhYAtzJBRiBELjfRRRcK6HqpXtCHnbntyITSsIxAiFwD54GCMzcysQC4lQkyAiFyDZwHCnrpWdCHnbntyIS3MESKgfNAwZkbmVgA3MoEiBQD54GCVKoX0IdoYWdu5IfwoePxL7o1DssIhMg1cB4oOHMjEwuAW5kgIxAi18B5oCC9D4X1pg87cyM/hA8djw8BLrVddGsclhEIkWvgPFBw5kYmFgC3MkFGIESugfNAQXofCisqWnhnNrYHA1JfdGschkghOHMjEwuAW5kAkUJ4BfR1uIaduZEfwgJgI7jo1jgMkWLgPFBw5kYmFgC3MkFGIESugfNAYX1vr6A/o4WduZEfwqLtolvjsIxAiFyCMzcysQC4lQkyAiFyCehoaML63sPsV8925DBEioHzQMGZG5lYANzKBBmBELkGzgMFvXBHO4chtSbJAF90axyWEQiRy0100YWCMzcysQC4lQkyAiFyuYkuulBA1wsr2hp25kZ+CIsJCBrvHBhcdGsclhEIkUtw5kYmFgC3MkFGIEQuAR0NTViHb9iZ245MeA5DpBg4DxScuZGJBcCtTIBIMXAeKKBKUQX0dZWGIaXTquSiW+OwjECIXAPngYIzNzKxALiVCTICIXINnAcKegH1vYeduZEfQgiU60W3xmGIFAPngYIzNzKxALiVCTICIXINnAcKemG4DsPO3MgPIQS41HbRrXFYRiBELsGZG5lYANzKBBmBELkEtLuwSs9hnYCN/oMBqS+6NQ5DpHATXXSh4MyNTCwAbmUCRAo30UUXCujrexPQpe8bduZGfgghwKW2MvBNBPiiW+OwjECIXIIzNzKxALiVCTICIXIJryDV68PuWvKtzAd20a1xWEYgRC430UUXCs7cyMQC4FYmyAiEyOUmuuhCAV0v6MOwkvoCCpQaPxiQ+qJb4zBECjfRRRcKztzIxALgViZApHATXXShgK4X0KWo97AzN/JDWExA0PiiW+OwjECIXIIzNzKxALiVCTICIXIJ6Ghowio9h6+qKglILro1DkOkcBNddKHgzI1MLABuZQJECjfRRRcK6DcB/RYLG6XTqiQw7DeY5ssAB4Y9qixcwN09Burv7mkAY3qKhas1qYweysIyAnVjYRGUfmBYBCWd6mJ+NKn0Hh7poeyhysIF3N1joP7ungYwpqdwtSYNeuv5UGXhAu7uMVB/d08DGNNTeKSHsocqQw6bVXUYIcMBUXPCIihx3e9o0nNYBMpVp7qYH02/6sPVmjToredDlSGHzao6jJDhgKg5YREoV677HU16Di/1A3G2DEpMsUUOf4qNqLbG1kvE8FI/EGfLQLkyxRY5Fl6AARHgHxhuFJLGtdXYgWFrFPZQZeEC7u4xUH93TwMY01PY71ryLdp614dPdTE/2jlsjcK47ne0dQ1bozDksFlVhxEyHBA1JxbGLTkMWKUqMGyNwh6qLFzA3T0G6u/uaQBjegq3AuLsyGG/a8m3aOtdH7ZGYchhs6oOI2Q4IGpO+FQX86OdY7Hwoap5GJA6MPwN2PFFgMNXVZUEZv0WHumk+AeGwYGBDLB8eF5gWIz2ovzqw6VoL8p6tDCOtsbCI50U+w2m+SLBBubREcN+g2n+OMH/kcMj+FY2wf9ldFIcOTyCb+4Go1WqyuikOHLYbzAL3EsdrVIVGJY0/lSBGRgG0dawmGc4HL5o6/B99S/ai3oexkO/3cKlPGfUG+p7u6HdpKho7/09x0O/ScM4z3l4X+9oK+orvZ3Rzvd7PPTbORam5jf+gWEQbQ2Lee4rmn54v6G+eukqlQ7XeOi3c7iU564fDqVn/fvq9WfUdX3jod+kYRxtjcViYY8qQw6bVXUYIcMBUXPCHlUWLuDuHgP1d/c0gDE9hT2qjOt+R1vX8KGq/cCwSP8PDJ/qYn401PcNj+CbCHBg+FQX86Ohvm8sFsagLoHhpcXD835gGAXieb8tGro+/Ot+I1tjXJeOtp7DQI0+xQWtysIQKdxEF10YJkA877dFQx/Gwnhp8fC8HxgmQDzvt0WTxsIlTE/m66i4R6tUhXUgOmmEbqKLLgyLh+cR1VJHYBQHhn/d72jrGgtjOps4UhUYltBfrVIVlhEIkSsWxg0WgtHv0ZU4UhUYltBfrVIVhkgRC/sNZoF7qaNVqiKHT3UxP9rwHDYfNzA2gtlhGXHrcNwc9htM8wPDHu5yHK2MLFmA9Y8ctkZhhB7FJGDhWNjvWvIt2u0Ni4fn/cCwomVUfTrrAqyXiOFf9xvZGuO6dDRU1PDxW55gdJ31W8SwojoODKxSFTEsmYCgMaImQcQwAeJ5vy0a+jk8zjq6Qh/To+RHDh+/nzqtcRge2GbLh+f9sKQxpqdoaxgF4nm/LdrtjYVdCt7BmJ4Cw62AODtiLBb26Hh8A7jUFhhuBcTZkWNhA7jUZgCX2gLDS4uH5/3AcCsgzo4YC0voqXFguBUQZ0eMhU91MT/aivaG/a4l36KhnmNhyQQEjQPDS4uH5/3AcCsgzo4YBmZg9CENy+Tn4Vh4BN9EgAPDXwKwa8RwVb8uTVQeLYDqGTHsdy35Fg31HvYoJgELl5HdbkeD1w5Kh091MT+a9H6Ohc3HDYyNYHZY19kZQF0Zcetw3OFTXcyPtqK9YQVIHRi2RmGEHsUkYOHyFSD1SCfF5ZWvAKl1JvVSD1J5u3vlL9Xz6nhMIxjppLi88j8JYJu99Sxvd6/871Ns4wT/V6+OwCpV5cXC4MBABDgwDMzA6EMaftw7lxM+fuvkV+tZv0WMhcXD835gWFEdBwZWqYoYBmZg9CENP+6dy4nFwhjURf8GhvHS4uF5PzDcCoizI4cJEM/7bdGksTCms4kjVYFhCf3VKlXhMkeDjjsWxg0WgtHv0ZU4UhUYbgXE2RHDEvqrVarCECliYZeCdzCmp8BwKyDOjhgL+w1mgXupo1WqIodPdTE/2vAWNh83MDaC2WEZcetw3Bz2G0zzA8Me7nIcrYwsWYD1jxy2RmGEHsUkYOFY2O9a8i2aFDUW9uh4/MDw0uLheT8wDMzA6EMalsnPw+Ff9xvZGuO6dLQ3fPyWJxhdZ/0WGPZwbbVMgoixWBgDVeoyv0fXiOFPAth2DgwK+qtVqsI6HJn8PEyIaIQy+Xk4LB6e9wPD6iBhevrRpOFf9xvZGuO6dLQ3fPyWJxhdZ/0WGPZwbbVMgoixcCsgzo4cBmr0KS5oVRaGSOEmuujCWBgcGIgAB4ZbAXF25LCiOg4MrFIVGPZwbbVMgsjhVk0iiByLxcIGcKktMLy0eHjeDwyrg4Tp6UeThn/db2RrjOvS0d7w8VueYHSd9Vtg2MO11TIJIoZbNYkgYiwsaYzpKdowFsZAlbrM79E1YhgcGIgAB4ZJAIWOAwOrVEU7v2GgRp/iglZlYdkZIDrFwubjBsZGMDssI24djpvDI/gmAhwY9ruWfIuGihb2KCYBC5eR3W5Hg9cOSoe/BGDXiOFTXcyPhiq9xcKnupgfbUV7w58EsO0cGBT0V6tUhXU4Mvl5mBDRCGXy83BYPDzvB4bVQcL09KNJw8dveYLRddZvgWEP11bLJIgYi8XCALcCgeERfBMBDgyf6mJ+NNT3jYVbAXF2xPCpLuZHQ33fWFgCsBEEhn2K6z5VBiZLwFhVKRpaeGnx8LwfGFYHCdPTj4Ya/nW/ka0xrktHQ13DKBDP+23R0O9rGKjRp7igVVkYIoWb6KILw5LGmJ6ioYYJEM/7bdHQ9cNYGC8tHp73A8OtgDg7cpgA8bzfFu0eC5cwPZmvo+IerVIV1oHopBG6iS66MCwenkdUSx2BURwY/nW/o63SWBjT2cSRqsCwhP5qlaqwjECIXLEwbrAQjH6PrsSRqsCwhP5qlaowRIpY2KXgHYzpKTDcCoizI4Z/3e9o+jcWNh83MDaC2WEZcetw3Bz2G8wC91JHq1RFDvsNpvmBYWsURuhRTAIWDnu4y3G0MrJkAdY/clhCf7VKVVhGIESuWPhUF/Oj3d+weHjeDwwrWkbVp7MuwHqJGP51v5GtMa5LR0NFDR+/5QlG11m/RQwrquPAwCpVEcOSCQgaI2oSRAwTIJ7326Khn8PjrKMr9DE9Sn7ksKQxpqdoaxgF4nm/LdrtjYUVIHVg2BqFEXoUk4CFy1eA1COdFJdXvgKk1vn7FFt5YQn91SpVYYgUsbABXGpzmfQUOSyhp8aBYWsURuhRTAIWjoW3xlZHMFkCxqpK0dawpO27YHpIAsNAjT7FBa3Kwm6iiy4Mn+pifrQbWrgVEGdHDvtdS75Fkw7DKBDP+23RpGECxPN+W7RhLBaWtAWGJfTUODDcCoizI8bCp7qYH21Fe8N+15Jv0VDPsVgsvAAD1ijsB4Y9qixcwN09Burv7mkAY3oKL8D6oZgELFzugnK5JJTLJdjdC1sl9UMxCVi4XF2dy73CpKoqCUhkakZJkcMeVcZ1v6Ota1gCVM8fGB60Z1dVtQCqZ/jBtdXyw4P2rMwHpgMYKIDqGRie7VmYJT1nOes2mLt7BT01DuNa8i28YxP8AaW2u+coH6ixl1hYpmaUdFVVC6B6hssoxcsPu2vJt6uqWgDVM+xy1LmEZWpGSe5a8u2qqhZA9Qzv2AR/QKnt7jnKB2rsJSxTM0oatGdXVbUAqme4jFK8/DCkkquqWgDVM4yQWoUhlbhryberqloA1TOMkFrFwiIwm13C9FBLxFgYjFapEgEODIsASwPDIhhdF0wlkcPiYUbVj7a+YfEwo+oXjd30FO0WJtHjN90aRw6LhxlVv+53NOkbC3tUGdf9jrauYY8qQw6bVXUYIcMBUXPCpDpiKgIcGG4FxNlL5PAfwexoL8rDc5hEj990axw5LILRdcFUEjkWFgFGDQy3AuLsJXJYBKPrgqkkclg8zKj6db+jSd9YWAR4DQyLhxlVv+53NOkbFsHoumAqiRwLiwDfAsOtgDh7iRgWDzOqfrQVNRb2qLJwAXf3GKi/u6cBjOkpLAJctAWGxcOMql/3OxrqORYWAdYHhsXDjKofbX3D4mFG1S8au+kp2i0sHmZU/brf0aRvmESP33RrHDkWCytAaskE1j8wrKiCAJfaIAbqSwBuNRJEe1E+68OHqvYDw47mXCgh1IqywLDfYJovAhwY9ruWfIu2SsPWKCww3AqIsyOHPYpJwMJlZLfb0SBh4bjLHA3Gwqe6mB9tXYexWPhxEx1NxwAlhMVgByWOOzDsN5jmiwAHhv2uJd+irdKwNQoLDLcC4uzIsfCpLuZHW9dhLBZ2NOdCCWEx2EGJ4w4M+w2m+SLAgWG/a8m3aKs0bI3CAsOtgDg7ctijmAQsXEZ2ux0NEhaOu8zRYCx8qov50dZ1GIvFwt+AHV8EOHxVVUlg1m/h4zcEuNTGI5gdMexRZchhs6oOI2Q4IGpO2KPKwgXc3WOg/u6eBjCmp7ABXGrjEcyOtoY9qozrfkdb31gYHBj8wLBHlYULuLvHQP3dPQ1gTE9hjypDDptVdRghwwFRc8InDCQ7njWOtr6x8KQn3J/OwypVvy1yLNFZZwmmXp2ts87O/L6kzUcpdJS6eqmbDw==

**Comment by lishpeth** [comment]
The error is gone, closing, thanks for the fix:)
