### ISSUE TITLE
haste.lua:43: invalid option in `format'

### ISSUE THREAD

**Issue by tjukoela** [ElvUI-TBC/ElvUI#28]
Message: Interface\AddOns\ElvUI\modules\datatexts\haste.lua:43: invalid option in `format'
Time: 04/16/17 15:36:58
Count: 2
Stack: [C]: ?
[C]: ?
Interface\AddOns\ElvUI\modules\datatexts\haste.lua:43: in function `onEnter'
...terface\AddOns\ElvUI\modules\datatexts\datatexts.lua:190: in function <...terface\AddOns\ElvUI\modules\datatexts\datatexts.lua:188>

**Comment by crumdidlyumshis** [comment]
This should already be fixed: https://github.com/ElvUI-TBC/ElvUI/issues/10
