### ISSUE TITLE
Raid Debuff Indicator Visual Bug

### ISSUE THREAD

**Issue by lishpeth** [ElvUI-TBC/ElvUI#281]
While joining a party or inviting people to you party, raiddebuff indicator shows random buffs of players as debuff. Reloading ui or changing zones fixes the visual bug... Also in party frames options, if I uncheck and then check the 'show dispellable debuffs' option it is fixed again...

![wowscrnshot_080417_185652](https://user-images.githubusercontent.com/28478416/28982676-5fcd2a28-795f-11e7-85de-8e71037b1f7b.jpg)

**Comment by Tremolo4** [comment]
Can conform. Can be fixed by Enabling and Disabling "Buffs" (not RaidDebuffs) for the RaidFrames.

**Comment by lishpeth** [comment]
With my raid frames, the visual bug appears where the raiddebuff indicator is. So when I enable and then disable raiddebuff indicator, the problem is fixed. I dont use 'Buffs' or 'Debuffs' with raid frames. Today I had joined a 40m raid and the visual bug appeared there, too. I had to reload everytime when someone joined...

**Comment by Tremolo4** [comment]
That's interesting.

For me, the buffs did not appear on the RaidDebuff indicator, but instead next to the frame of the unit (essentially on top of another unit's frame). I don't use Buffs either, but still Enabling and Disabling them helped, no reload needed.

**Comment by lishpeth** [comment]
I also have seen that when I am on hunter, the visual bug doesnt appear even if 'show dispellable debuffs' checked. Maybe it is because hunter cant dispel anything from the friendly targets but my priest can... 
I had to reload because sometimes Elvui's config window for some reason is bugging, too and the dropdown options disappears. It dissappeared again and I reloaded:)

**Comment by Tremolo4** [comment]
The disappearing in config menu is a different issue: https://github.com/ElvUI-TBC/ElvUI/issues/271

offtopic: For faster (re-)loading I can wholeheartedly recommend [ImpulseBooster](https://github.com/Warlockbugs/impulse-booster) :)
