### ISSUE TITLE
[Feature Request] Select sticky chats

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#284]
It's really annoying that the sticky chat feature includes custom channels (lfg, general etc.), whisper chat, yell and raid warning. Imho this feature should only work at raid, party, officer and say channel. But every player has another priorities. For this case it would be awesome if you could select the channel which you want to be sticky like in prat or chatter.

**Comment by Tremolo4** [comment]
I had implemented this in #266, but it was rejected because it is not a functionality of original ElvUI.
