### ISSUE TITLE
Raid Debuff Indicator Visual Bug continues

### ISSUE THREAD

**Issue by lishpeth** [ElvUI-TBC/ElvUI#285]
While joining a party or inviting people to you party, raiddebuff indicator shows random buffs of players as debuff. Reloading ui or changing zones fixes the visual bug... Also in party frames options, if I uncheck and then check the 'show dispellable debuffs' option it is fixed again...
This issue only belongs to **Party Frames**. I dont have any visual bug appearing with raiddebuff indicator on Raid Frames...

![wowscrnshot_080417_185652](https://user-images.githubusercontent.com/28478416/28982676-5fcd2a28-795f-11e7-85de-8e71037b1f7b.jpg)

**I have updated my elvui with deleting the old one and the issue still continues as of today 05/08/2017**

![wowscrnshot_080517_220536](https://user-images.githubusercontent.com/28478416/28998025-73a9b644-7a2a-11e7-9a35-a4cf1aa915c5.jpg)

**Comment by Pziko** [comment]
ELVUI is nice MOD/ADDON and I do appreciate their work. But you should use another unitframes. There's many game-breaking issues related to them and not even on their priority list.

**Comment by lishpeth** [comment]
I am actually happy with current state of Elvui right now. The only problem for me is this visual bug when you have character that can dispel something. 'Show dispellable Debuffs' checked or unchecked doesnt matter, this visual bug occurs if your class has an ability to dispel from friendly players, thats all. They have bringed a fix about this and they will do it again I am sure. I am really in love with their work...

**Comment by Tremolo4** [comment]
Can confirm. Happens since the uOF update. Usually after joining a raid group or re-logging into one.
Can be worked around like so: https://www.youtube.com/watch?v=ttGq1xpUVYk

**Comment by Tremolo4** [comment]
Hmm, I do not have this problem. Did you try resetting your settings/WTF folder (after making backup of course)?
