### ISSUE TITLE
raid issue

### ISSUE THREAD

**Issue by sckush** [ElvUI-TBC/ElvUI#286]
![image](https://user-images.githubusercontent.com/25095351/29054530-5669fb06-7c29-11e7-8364-5e2f70956f5c.png)
sometimes the buff icon will show, i never set that

**Comment by lishpeth** [comment]
#285 This issue happens with me too in 40m raid groups. Also in party frames raid debuff indicator visual bug continues...

**Comment by Tremolo4** [comment]
Can confirm. Happens since the uOF update. Usually after joining a raid group or re-logging into one.
Can be worked around like so: https://www.youtube.com/watch?v=ttGq1xpUVYk
(In the video the bottom is cut off, because my resolution aspect ratio is 16:10)

**Comment by Bunny67** [comment]
Check "Restore Defaults". I think this will help

**Comment by Tremolo4** [comment]
Tried it, did not help. Only reset all settings :D (but I have a backup)

**Comment by Bunny67** [comment]
:(

**Comment by Tremolo4** [comment]
Hmm until recently, on my server, there was a bug that you could not see your own Buff Durations after relogging or reloading or going through a portal loading screen etc. We fixed that, maybe that's why the bug does not happen to you?

**Comment by Tremolo4** [comment]
Or maybe it's not that.
More footage: https://youtu.be/QvlorENGG6A
Debuffs are shown sometimes as well and can be fixed by toggling BUFFS.

**Comment by Tremolo4** [comment]
That fixes the problem for me.
