### ISSUE TITLE
Party/Raid frame while in raid is broken

### ISSUE THREAD

**Issue by frozen-void** [ElvUI-TBC/ElvUI#287]
I'm not sure if those are two separate issues or if they have the same source.

Case 1: The raid frame is shown correctly, but the party frame is missing.
Case 2: The raid frame is missing and the party frame shows the members of group 1.

Case 1 seems to be "standard" and case 2 only happened with <5 group members, but I don't know what the actual trigger for that behavior is.

**Comment by Tremolo4** [comment]
That's not a bug, you can configure when each frame should be visible in the Visibility settings (works like a macro).

![visibility](https://user-images.githubusercontent.com/818793/29245767-ababc64e-7fe4-11e7-91f2-c0abc45aa1ef.png)

**Comment by frozen-void** [comment]
The raid frame is now working as I would expect it to, but the group frame still behaves strange. In a normal raid group it always shows the members of group 1 and in a battleground it shows nothing.

**Comment by Bunny67** [comment]
uncheck "Smart Raid Filter"
