### ISSUE TITLE
Request: Possible to Backport "ElvUI_LocPlus" ?

### ISSUE THREAD

**Issue by q3fuba** [ElvUI-TBC/ElvUI#291]
Hi there,
tried to use **ElvUI Location Plus** from 7.x but there are many errors :/
maybe its possible to backport it to make it work with ElvUI-TBC?

greetings

**Comment by crumdidlyumshis** [comment]
Already done :) 
https://github.com/ElvUI-TBC/ElvUI_LocPlus

**Comment by q3fuba** [comment]
wow dude...
many thanks :))
