### ISSUE TITLE
Tooltip: Health Bar Text visible after Reload although disabled

### ISSUE THREAD

**Issue by fuba82** [ElvUI-TBC/ElvUI#292]
Hi there,
The Tooltip Health Bar Text is still Visible after reload or relog but it is also disabled in the Settings.
![image6](https://user-images.githubusercontent.com/11580974/29337311-258b7378-8211-11e7-8dea-e83aca40f313.png)

**Comment by Bunny67** [comment]
Could not reproduce

**Comment by q3fuba** [comment]
> Could not reproduce  

anyway the bug is still present ^^

Reproduce:
1. ESC -> ElvUI -> Tooltip -> Health Bar -> UN-Check "Text"
2. Relog/Reload/Restart the Game
3. View the Tooltip -> Text is Visible
4. ESC -> ElvUI -> Tooltip -> Health Bar -> "Text" is unchecked but Visible in the Tooltip

**Comment by Loaal** [comment]
Can't reproduce.
Please provide your addon list.

**Comment by q3fuba** [comment]
There is no addon list...  
Becasue there is no addon active except **!Compatibility**, **!DebugTools**, **ElvUI** and **ElvUI_Config**

also tried with ```/luaerror on```
what does die same execpt enable **!Compatibility** and **!DebugTools**, what is also an error, but this is another issue ;)

Means, the error still exists with last repo!

**Comment by crumdidlyumshis** [comment]
This is very strange indeed. I tried it myself, but everything works as it should. :/

**Comment by q3fuba** [comment]
yep but its not a gamebreaking bug ^^

**Comment by crumdidlyumshis** [comment]
still occurring?

**Comment by q3fuba** [comment]
i dont know becasue im too busy now :/
but i will test it as soon as possible with a complete new installation!

**Comment by crumdidlyumshis** [comment]
Strange, I’ll reinstall ElvUI in a different profile and see if notice anything again. What client are you using? enGB, enUS, etc...?

**Comment by q3fuba** [comment]
using the enGB client
first was from excalibur and now from warmane becasue i thought maybe its the client fault
