### ISSUE TITLE
Whispers from other addons

### ISSUE THREAD

**Issue by frozen-void** [ElvUI-TBC/ElvUI#295]
If the chat settings are enabled, whispers from other addons are shown.
These messages are probably from deadly boss mods and really annoying:
![spam](https://user-images.githubusercontent.com/15674083/29577538-1878ada8-876c-11e7-861f-8c248932b9e5.PNG)

**Comment by Bunny67** [comment]
Do you know which addon whispers?

**Comment by frozen-void** [comment]
I did a little testing and found out that Deadly Boss Mods (v3.22) uses whispers starting with "LVBM"/"LVPN" for syncing reasons and normally hides them. As soon as the chat settings from ElvUI are enabled, the messages are no longer hidden.

**Comment by Tremolo4** [comment]
I also have this problem, I'm using DBM as well.

**Comment by Loaal** [comment]
[Fix](https://github.com/ElvUI-TBC/ElvUI_Enhanced/commit/7b437a175e099eb7198102f46830caeaa1b60a94) added to [ElvUI_Enhanced](https://github.com/ElvUI-TBC/ElvUI_Enhanced) plugin.
