### ISSUE TITLE
Minimap Auras Reminder

### ISSUE THREAD

**Issue by lierox90** [ElvUI-TBC/ElvUI#298]
![image](https://user-images.githubusercontent.com/4543689/29743511-14683a3c-8a94-11e7-895e-cee6c0e1f6e9.png)
As you can see Reminders shows only 5 buffs, while in TBC theres MUUUCH more, this should be updated accordingly.

**Comment by crumdidlyumshis** [comment]
This is dynamically updated depending on your Raid Buffs, major buffs, etc...

**Comment by lierox90** [comment]
I dont think you get the point, i dont care whether its dynamic or not, i care about that it is missing placeholder for other buffs, this is outlet of pandaria, where buffs had much different stats increasd rather than in tbc, for ex a player in tbc can have bok and gift stacking, while on pandaria it is the same buff that doesnt stack. Get this fixed pls.

**Comment by crumdidlyumshis** [comment]
I don't care whether I "get the point". For now, we will keep this closed. Maybe we will update this when we feel like it, since this isn't a full time job or a job that benefits us in any financial way... Next time rethink your demands towards free labor. We might just "Get this fixed" one day...
