### ISSUE TITLE
Libraries\oUF_Plugins\oUF_GPS\oUF_GPS.lua:33: attempt to call global 

### ISSUE THREAD

**Issue by tjukoela** [ElvUI-TBC/ElvUI#30]
Message: ...dOns\ElvUI\Libraries\oUF_Plugins\oUF_GPS\oUF_GPS.lua:33: attempt to call global 'GetPlayerFacing' (a nil value) Time: 04/18/17 01:37:21 Count: 2 Stack: [C]: in function `GetPlayerFacing' ...dOns\ElvUI\Libraries\oUF_Plugins\oUF_GPS\oUF_GPS.lua:33: in function <...dOns\ElvUI\Libraries\oUF_Plugins\oUF_GPS\oUF_GPS.lua:28> ...dOns\ElvUI\Libraries\oUF_Plugins\oUF_GPS\oUF_GPS.lua:53: in function <...dOns\ElvUI\Libraries\oUF_Plugins\oUF_GPS\oUF_GPS.lua:38>

**Comment by crumdidlyumshis** [comment]
I just fixed this today. https://github.com/ElvUI-TBC/ElvUI/commit/95b2dd7afea9798ae90ff3c1888e157281b6f00b

Please update to latest version. Thanks!
