### ISSUE TITLE
[Low Priority]Castbar Text: "Opening - No Text"

### ISSUE THREAD

**Issue by q3fuba** [ElvUI-TBC/ElvUI#302]
hi there,
i found a **low priority** style bug.

When opening e.g an "Un'Goro Dirt Pile" the Castbar shows:
![image](https://user-images.githubusercontent.com/11580974/29922292-4a7ee5c0-8e55-11e7-9b94-7c425c8bc57c.png)

Maybe you can correct this if you have the time :)

**Comment by crumdidlyumshis** [comment]
Actually this is a server issue. I have seen this happen on multiple servers i've played on in the past, including vanilla and wrath. Thank you for the report though!

**Comment by q3fuba** [comment]
oh sorry then
i just wrote becasue the original castbar show no text at all :D

**Comment by crumdidlyumshis** [comment]
Np closing 🤓
