### ISSUE TITLE
[Bug] "WorldStateCaptureBar" moves inside the Minimap on Update

### ISSUE THREAD

**Issue by q3fuba** [ElvUI-TBC/ElvUI#306]
Somtimes the "WorldStateCaptureBar" moves inside the Minimap on update.
It also moves Back to the middle of the screen,,, sometimes un update.
![wowscrnshot_091317_023115](https://user-images.githubusercontent.com/11580974/30355853-229f688c-9836-11e7-90bc-812b7ab3f163.jpg)
![wowscrnshot_091317_023100](https://user-images.githubusercontent.com/11580974/30355849-1d5a8d34-9836-11e7-86d3-d30bdfec9cb2.jpg)

maybe the moving comes from [\ElvUI_AddOnSkins](https://github.com/ElvUI-TBC/ElvUI_AddOnSkins) im note sure

**Comment by q3fuba** [comment]
Yep it seems this bug is from [ElvUI_AddOnSkin](https://github.com/ElvUI-TBC/ElvUI_AddOnSkins)  
Becasue without [ElvUI_AddOnSkin](https://github.com/ElvUI-TBC/ElvUI_AddOnSkins) it works.

**Comment by crumdidlyumshis** [comment]
fixed? close?

**Comment by q3fuba** [comment]
dont know i too busy to test it now, sry
