### ISSUE TITLE
Pet happiness not shown in low resolution mode

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#309]
I play on my notebook with a 1366x768 resolution and the pet hapiness is completly gone:
![wowscrnshot_091417_122033](https://user-images.githubusercontent.com/6052285/30424746-2a299bd8-9947-11e7-9379-91483cf28920.jpg)

**Comment by fatlus** [comment]
Very good, but the bar is now a little bit too long. The happiness indicator should take place inside the bar not behind the bar
![wowscrnshot_091517_114454](https://user-images.githubusercontent.com/6052285/30476855-9b534bfa-9a0b-11e7-9cc7-348cc4326b40.jpg)

**Comment by Apollyonn** [comment]
Change frame orientation to left or right

**Comment by Apollyonn** [comment]
It should be ok now with middle orientation too.
