### ISSUE TITLE
Better solution for target frame texts with low resolution mode?

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#310]
As you can see the health text has an overlay with the level of the mob. Is there another solution to get a proper text interface before I edit the position of these text?
![wowscrnshot_091417_182206](https://user-images.githubusercontent.com/6052285/30441545-101e7a82-997a-11e7-8323-194d1fd1c80a.jpg)

**Comment by Apollyonn** [comment]
You can change the name tag from [name:medium] to [name:short].

**Comment by fatlus** [comment]
The name text should also be moved 15 pixels to the left side. Would be cool if these settings were standard after completing the wizard.
