### ISSUE TITLE
Currency symbols instead of g/s/c texts

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#311]
As you can see on the screenshot the currency symbols are active in the chat when repairing items and in the tooltip. It is possible to change the symbols to the g/s/c texts?
![wowscrnshot_091517_001525_li](https://user-images.githubusercontent.com/6052285/30458405-ad139fbc-99ab-11e7-849b-600b846c10ee.jpg)

**Comment by crumdidlyumshis** [comment]
hmmm, screenshot not loading =O

**Comment by fatlus** [comment]
Sorry, you were fast. I forgot to blurry the chat :)

**Comment by crumdidlyumshis** [comment]
Oh haha, np, I have quick fingers ^^

**Comment by fatlus** [comment]
Fixed with #323
