### ISSUE TITLE
Riad-Manager window is bugged.

### ISSUE THREAD

**Issue by qvortx** [ElvUI-TBC/ElvUI#316]
Riad-Managering window is bugged in combat. When in combat  i cant swap raid members because i see only black window. screenshot: 
![wowscrnshot_092717_211031](https://user-images.githubusercontent.com/29815703/30931959-c0a29326-a3ce-11e7-901b-b9dc2a7446c2.jpg)

**Comment by qvortx** [comment]
up

**Comment by fatlus** [comment]
Doesn't have this issue, maybe an addon interference at your side?

**Comment by crumdidlyumshis** [comment]
Please list all the addons you have. Unable to reproduce.

**Comment by qvortx** [comment]
Thanks for answer! there is list of my addons: https://i.imgur.com/lx7vh5t.jpg

**Comment by qvortx** [comment]
up!

**Comment by crumdidlyumshis** [comment]
Have you tried the latest update @qvortx?
@Apollyonn fixed this and closed it already. Try the latest and report back.

**Comment by crumdidlyumshis** [comment]
I’m addition to this fix @Apollyonn made, I should note that the way the raid manager works is indeed working as it should. This should behave like your seeing in “in combat”

**Comment by qvortx** [comment]
up

**Comment by Bunny67** [comment]
Disable "Raid Control". Maybe it will be deleted

**Comment by qvortx** [comment]
Guys thank you for your help but "Gladdy" block my raid frames.
