### ISSUE TITLE
Error during talent speccing as shaman

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#322]
Message: Interface\FrameXML\Cooldown.lua:3: attempt to compare number with nil
Time: 10/29/17 11:36:12
Count: 8
Stack: Interface\AddOns\Ace2\AceEvent-2.0\AceEvent-2.0.lua:299: in function `TriggerEvent'
Interface\AddOns\Ace2\AceEvent-2.0\AceEvent-2.0.lua:910: in function <Interface\AddOns\Ace2\AceEvent-2.0\AceEvent-2.0.lua:903>

**Comment by crumdidlyumshis** [comment]
Looks like a conflict with the Ace2 addon you have installed.

**Comment by fatlus** [comment]
Yepp, closed
