### ISSUE TITLE
Glitchy UI on lower resolution

### ISSUE THREAD

**Issue by nadszeg** [ElvUI-TBC/ElvUI#326]
Hi!

 I'd like to report a visual glitch - when I play on my bigger laptop (it has a 1920x1080 screen), everything seems to be good, but when I use my travel laptop to play (it has a 1366x768 screen) some elements of the UI glitch out. The most notable thing is the bag: https://imgur.com/a/QioFQ
Elements float out of their boxes... I have a MoP client on my travel laptop too, and that version of the ElvUI doesn't have any glitches like this, so this must be something in the code. 
Can you fix it? :)

**Comment by crumdidlyumshis** [comment]
Hmm, cannot reproduce.

**Comment by crumdidlyumshis** [comment]
So basically if you change the size of the bag slots +/- 2 numbers from where your bag slots size is at now, it should fix it. This would require a lot of hack-fixes which is not going to happen. Hope this helps!
