### ISSUE TITLE
rnd raid error

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#328]
Message: ...terface\AddOns\ElvUI\modules\skins\blizzard\raid.lua:93: attempt to index local 'pullOutFrame' (a nil value)
Time: 11/12/17 21:29:49
Count: 3
Stack: [C]: ?
...terface\AddOns\ElvUI\modules\skins\blizzard\raid.lua:93: in function <...terface\AddOns\ElvUI\modules\skins\blizzard\raid.lua:92>
[C]: in function `RaidPullout_Update'
Interface\AddOns\Blizzard_RaidUI\Blizzard_RaidUI.lua:677: in function `RaidPullout_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

**Comment by crumdidlyumshis** [comment]
I could be wrong, but this looks like it could be a server issue?

**Comment by fatlus** [comment]
Happens if you move out a group or player from the Blizzard raid manager to the UI INFIGHT.
