### ISSUE TITLE
Chat jumps always to bottom after receiving a new message

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#329]
If you scroll up the chat to read an old message the chat will jump to the actual message if you receive a new message. This is a little bit annoying to read old messages and scroll every time up when a message appears in a channel (world, general, group/raid, guild etc.)

**Comment by crumdidlyumshis** [comment]
try latest

**Comment by fatlus** [comment]
The 2nd option. I will try your fix soon.

**Comment by fatlus** [comment]
Happens again after a few settings. I scroll up, stop, read a message and after a few seconds the chat will jump to the bottom. It takes 10-15s

**Comment by crumdidlyumshis** [comment]
That’s actually normal I believe. Wrath version does this too. It waits around 10-15 seconds before jumping back down.

**Comment by crumdidlyumshis** [comment]
https://github.com/ElvUI-TBC/ElvUI/blob/master/ElvUI/modules/chat/chat.lua#L182

**Comment by crumdidlyumshis** [comment]
Close?

**Comment by fatlus** [comment]
Sure, i am stupid...
