### ISSUE TITLE
ActionsBar can't  be setup

### ISSUE THREAD

**Issue by tjukoela** [ElvUI-TBC/ElvUI#33]
We can't setup actions bar, if yes what is the process ?

**Comment by crumdidlyumshis** [comment]
Yeah I've been looking into this. @Bunny67 has an idea.

**Comment by crumdidlyumshis** [comment]
fixed https://github.com/ElvUI-TBC/ElvUI/commit/eb65e7b6b64e5b68ee3722dc8b4186bb78db76fa
