### ISSUE TITLE
Addon not showing up in addon list

### ISSUE THREAD

**Issue by Nerheim** [ElvUI-TBC/ElvUI#330]
Hello,
I downloaded the zip folder and extracted it into my addons folder in wow, which I have 10-15 other addons in that are working.  When i open up addon list I cannot find elvui or chronometer on the list.

**Comment by Tremolo4** [comment]
The zip folder contains another subfolder which contains the actual ElvUI addons (4 folders). You need to move them out of the subfolder, which should be called `ElvUI-master`

**Comment by Nerheim** [comment]
Worked, thank you very much!
