### ISSUE TITLE
Not Showing Configuration Options

### ISSUE THREAD

**Issue by EnvisionMore** [ElvUI-TBC/ElvUI#331]
Just downloaded and installed, getting this issue and cannot customize anything. Did I do something wrong? 

https://i.imgur.com/l07C8Oh.jpg

Thanks!

**Comment by crumdidlyumshis** [comment]
Wow this is the first! Can you provide a list of your current addons installed with ElvUI?

**Comment by EnvisionMore** [comment]
Sure thing, here you are.
https://i.imgur.com/Ac8vXfP.jpg
https://i.imgur.com/YG3HZPh.jpg
https://i.imgur.com/rFhUmNW.jpg

**Comment by crumdidlyumshis** [comment]
I downloaded and installed all those addons listed in your pics. I cannot reproduce what you're seeing. :/
