### ISSUE TITLE
Castbar sometime dissapears during crafting

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#336]
If you craft a lot items (for example Bolt of Netherweave) the castbar dissapears. The crafting process continues but you don't see the castbar.

**Comment by cwtopel** [comment]
I can confirm I've had this happen to me as well.

**Comment by Tr1n1ty1** [comment]
This can also (rarely) happen with quartz or other castbar addons because those addons merge all casts to one mega cast, so it might be a general bug rather then elvui specific

**Comment by fatlus** [comment]
I've used Quartz over 2 years and I can't remember that this happened. With ElvUI this occur every 2nd oder 3rd crafting process.
