### ISSUE TITLE
LUA Error on Bag Opening

### ISSUE THREAD

**Issue by Ghanrak** [ElvUI-TBC/ElvUI#34]
Message: Interface\AddOns\ElvUI\modules\bags\bags.lua:197: attempt to index local 'button' (a nil value)
Time: 04/23/17 01:06:55
Count: 1
Stack: [C]: ?
Interface\AddOns\ElvUI\modules\bags\bags.lua:197: in function `SetSearch'
Interface\AddOns\ElvUI\modules\bags\bags.lua:151: in function <Interface\AddOns\ElvUI\modules\bags\bags.lua:123>

**Comment by kinappy** [comment]
I'm getting this error when I first login:
Message: Interface\AddOns\ElvUI\modules\bags\bags.lua:646: attempt to call upvalue 'GetContainerItemQuestInfo' (a nil value)
Time: 05/11/17 19:42:55
Count: 4
Stack: [C]: ?
Interface\AddOns\ElvUI\modules\bags\bags.lua:646: in function `UpdateKeySlot'
Interface\AddOns\ElvUI\modules\bags\bags.lua:608: in function `Layout'
Interface\AddOns\ElvUI\modules\bags\bags.lua:704: in function <Interface\AddOns\ElvUI\modules\bags\bags.lua:685>




This is returned when I first open my bags but only the first time.
Message: Interface\AddOns\ElvUI\modules\bags\bags.lua:197: attempt to index local 'button' (a nil value)
Time: 05/11/17 19:43:07
Count: 1
Stack: [C]: ?
Interface\AddOns\ElvUI\modules\bags\bags.lua:197: in function `SetSearch'
Interface\AddOns\ElvUI\modules\bags\bags.lua:151: in function <Interface\AddOns\ElvUI\modules\bags\bags.lua:123>

**Comment by crumdidlyumshis** [comment]
I'll check this out when I get home. Thanks for the bug reports!

**Comment by denellum** [comment]
I can replicate this as well : 

Message: Interface\AddOns\ElvUI\modules\bags\bags.lua:646: attempt to call upvalue 'GetContainerItemQuestInfo' (a nil value)
Time: 05/11/17 14:40:15
Count: 4
Stack: (tail call): ?
[C]: ?
Interface\AddOns\ElvUI\modules\bags\bags.lua:646: in function `UpdateKeySlot'
Interface\AddOns\ElvUI\modules\bags\bags.lua:608: in function `Layout'
Interface\AddOns\ElvUI\modules\bags\bags.lua:704: in function <Interface\AddOns\ElvUI\modules\bags\bags.lua:685>

**Comment by kinappy** [comment]
I have checked this on two different BC clients tonight.

I downloaded the client from Warmane and I don't get these bag errors and things appear to work OK.

I only get this when I use the client from Excalibur which I might have had for six months. 

On both clients I deleted cache, wft and interface before adding ElvUI.

**Comment by denellum** [comment]
I am using the hellfire client.and noticed it only happens once you get a quest item thats a key.

**Comment by kinappy** [comment]
I just deleted my keys from the Excalibur client and no longer get these errors

**Comment by crumdidlyumshis** [comment]
The clients shouldn't matter if at all as long as they are version 2.4.3 patched. The function sounds like it's wrong. Probably a simple fix. Can't verify yet as I'm still at work. I'll check later when I'm at my computer :)

**Comment by crumdidlyumshis** [comment]
check cae9a137286a3224c1585e48d76eb2dac36de6de

**Comment by crumdidlyumshis** [comment]
another update a8bbb0a35aa439880aeb7928ee7af2c9208a2ef1

**Comment by denellum** [comment]
trying now, was pooped out by the time the update came out. will report back, thank you for your help with this crumdidlyumshis!

**Comment by kinappy** [comment]
For me this is now working fine

**Comment by crumdidlyumshis** [comment]
No problem! It was a wrath function that I really couldn't backport. Basically highlighted the border of quest items in your bags.
