### ISSUE TITLE
Cooldown text not visible on necklace

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#343]
The cooldown text on the necklace (black temple port necklace) is not visible after the latest update

**Comment by Crumdidlyumshis** [comment]
http://www.wowhead.com/item=32757/blessed-medallion-of-karabor ?

**Comment by fatlus** [comment]
Yes, other ElvUI user with older versions haven't this issue

**Comment by fatlus** [comment]
Nevermind, it was something other
