### ISSUE TITLE
Guild datatext update frequency too slow after latest update

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#344]
It takes approx 30-45s to refresh the guild list when a new guild member comes online or goes offline.

**Comment by Crumdidlyumshis** [comment]
Try now

**Comment by fatlus** [comment]
Yes, looks better!

**Comment by fatlus** [comment]
Still not very accurate :(

**Comment by Crumdidlyumshis** [comment]
I believe @Loaal is going to update this. I passed it onto him.

**Comment by fatlus** [comment]
Now the number of the online guild member of the datatext is only updated when hover over the datatext itself with the mouse.
