### ISSUE TITLE
Search function not finding Medallion of Karabor

### ISSUE THREAD

**Issue by PopkornKevin** [ElvUI-TBC/ElvUI#351]
Seems that when searching for specifically Medallion of Karabor the search doesn't find the item.

This cost a warlock in our guild 3 days of raiding because he couldn't find the item in his bags. He raged and blamed the server for deleting his item.

![medalion](https://user-images.githubusercontent.com/25029094/35360341-b350e2bc-015d-11e8-88b8-59df773b8e3d.jpg)

**Comment by Crumdidlyumshis** [comment]
Will look into it, however should not be an excuse for not finding the item. This UI never existed in TBC.

**Comment by PopkornKevin** [comment]
Don't worry, not blaming it on the UI it was just funny.

**Comment by Fanquar** [comment]
it's possible you added your medallion to the "don't move/reshuffle this item" filter in the Bags menu? the tooltip on that also describes it will not search for it either

**Comment by cwtopel** [comment]
You need to use the correct modifiers with the bag search. To find gear, you need to add 'n:' to the beginning of the search query. 

Examples:
`n:medallion`
`n:karabor`
