### ISSUE TITLE
WIM Error

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#352]
A forwarded error:

Message: Interface\AddOns\WIM\WIM.lua:2035: bad argument #1 to 'strlower' (string expected, got nil)
Time: 01/27/18 12:57:15
Count: 1
Stack: [C]: in function `strlower'
Interface\AddOns\WIM\WIM.lua:2035: in function `WIM_FilterResult'
Interface\AddOns\WIM\WIM.lua:2000: in function `WIM_FilterResult_Interface'
Interface\AddOns\WIM\WIM.lua:545: in function `filterFunc'
Interface\AddOns\ElvUI\modules\chat\chat.lua:809: in function `ChatFrame_MessageEventHandler'
Interface\AddOns\ElvUI\modules\chat\chat.lua:1397: in function `DisplayChatHistory'
Interface\AddOns\ElvUI\modules\chat\chat.lua:1612: in function `Initialize'
Interface\AddOns\ElvUI\modules\chat\chat.lua:1700: in function <Interface\AddOns\ElvUI\modules\chat\chat.lua:1699>
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:155: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:155>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
Interface\AddOns\ElvUI\core\core.lua:966: in function `InitializeModules'
Interface\AddOns\ElvUI\core\core.lua:1078: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:146: in function <...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:146>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:91: in function `Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

When opening the chat history:
Message: Interface\AddOns\ElvUI\modules\chat\chat.lua:401: attempt to index global 'CopyChatFrame' (a nil value)
Time: 01/27/18 12:59:18
Count: 2
Stack: [C]: ?
Interface\AddOns\ElvUI\modules\chat\chat.lua:401: in function `CopyChat'
Interface\AddOns\ElvUI\modules\chat\chat.lua:338: in function <Interface\AddOns\ElvUI\modules\chat\chat.lua:336>

Used addon version:
https://wow.curseforge.com/projects/project-2832/files/72750

**Comment by Tremolo4** [comment]
Maybe due to mangos/blizzardui SMSG_WHO bug?
Try this fixed WhoLib version.
[WIM-2.4.15_betterwhofix.zip](https://github.com/ElvUI-TBC/ElvUI/files/1671180/WIM-2.4.15_betterwhofix.zip)

**Comment by Tremolo4** [comment]
For anyone interested, here is an actual fixed version (untested)
[WIM-2.4.15_betterwhofix_libwho-2.0.zip](https://github.com/ElvUI-TBC/ElvUI/files/2031875/WIM-2.4.15_betterwhofix_libwho-2.0.zip)

**Comment by Tremolo4** [comment]
This error is actually not caused by the SMSG_WHO bug. See [here](https://github.com/ElvUI-TBC/ElvUI/issues/473#issuecomment-642331129)
