### ISSUE TITLE
Error when switching trinkets

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#356]
Message: Interface\FrameXML\PaperDollFrame.lua:1023: attempt to index field 'spellCrit' (a nil value)
Time: 02/28/18 16:24:21
Count: 1
Stack: [C]: ?
Interface\FrameXML\PaperDollFrame.lua:1023: in function <Interface\FrameXML\PaperDollFrame.lua:1018>
...ddOns\ElvUI_Enhanced\Modules\Misc\characterFrame.lua:169: in function <...ddOns\ElvUI_Enhanced\Modules\Misc\characterFrame.lua:169>
...ddOns\ElvUI_Enhanced\Modules\Misc\characterFrame.lua:838: in function `PaperDollFrame_UpdateStatCategory'
...ddOns\ElvUI_Enhanced\Modules\Misc\characterFrame.lua:878: in function `PaperDollFrame_UpdateStats'
...ddOns\ElvUI_Enhanced\Modules\Misc\characterFrame.lua:1726: in function <...ddOns\ElvUI_Enhanced\Modules\Misc\characterFrame.lua:1712>
[C]: ?

**Comment by Kilokambala** [comment]
When https://www.wowhead.com/item=38290/dark-iron-smoking-pipe  on https://www.wowhead.com/item=28241/medallion-of-the-horde
