### ISSUE TITLE
Tooltips are breaking during inspecting after few moments

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#357]
If you inspect a player the tooltip of an equipped item isn't shown. It happens totally random and there is no error.
![wowscrnshot_030318_103652](https://user-images.githubusercontent.com/6052285/36932786-02834f58-1ecf-11e8-8b29-776741e7d902.jpg)

**Comment by fatlus** [comment]
I don't have installed one of these addons in TBC. This bug seems to be fixed since a lot of weeks/months. I think it can be closed.

**Comment by VideoPlayerCode** [comment]
@fatlus Ok it's time to re-open this ticket. I have found what causes it.

- First, inspect somebody.
- Second, hover your mouse over the unit frames in your party (haven't tested in raids).
- Try to hover an item again. If you still see a tooltip, continue to hover over party frames. Eventually, the item tooltips will break.
- If you want the tooltips to work again, continue to hover over various party frames.

The GearScoreLite addon is installed on my 2.4.3, which may be relevant.

**Comment by VideoPlayerCode** [comment]
Oh and ... @Apollyonn
