### ISSUE TITLE
Threat / aggro highlighting on unit frames not working

### ISSUE THREAD

**Issue by Hardour** [ElvUI-TBC/ElvUI#368]
Hi

I've been trying to make threat on unit frames (party and raid) work. Not sure if it is just me, but I just can't make it work. I've got a Threat 2.0 library installed via Omen, but it is still not working. Is this a recognized issue?

Many thanks for the great work done on this addon.

**Comment by Tremolo4** [comment]
Threat highlighting does not work out of the box in ElvUI-TBC.

You can use [this](https://github.com/Tremolo4/ElvUI_ThreatDisplayFix) to make it (mostly) work.
