### ISSUE TITLE
Color nameplates on aggro / thread available ?

### ISSUE THREAD

**Issue by VKosev** [ElvUI-TBC/ElvUI#370]
Hello.
Is there any option available to color the nameplates based on aggro ?
For example when aggro is on me nameplates to be colored red and when I'm not aggroed by the mob nameplates to be green or yellow.

**Comment by Tremolo4** [comment]
It's not available in default ElvUI-TBC.
I have implemented it [here](https://github.com/Tremolo4/ElvUI/tree/nameplate_threat_glow).
I think it works quite well but it's just a prototype. There is no option to turn it off. Don't know whether I'll work on it more.
