### ISSUE TITLE
No Raid/HC ID overview in time datatext

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#371]
Unlike as the WotLK version you cannot see the instance IDs on the time datatext

**Comment by fatlus** [comment]
I wrote a workaround based on the old API commands. Instance pictures aren't available in TBC because of missing calendar API. I combinded the instance id and name to one string to match the 2 row function of the gametooltip API. If there is a another solution you can change it. I don't know if TBC can seperate raid and heroic instance ids. I combinded both in one overview, maybe it is possible to seperate them.
![wowscrnshot_070118_132917](https://user-images.githubusercontent.com/6052285/42134006-86d1ceac-7d33-11e8-9d6b-6141973be29f.jpg)

`local E, L, V, P, G = unpack(ElvUI);
local DT = E:GetModule("DataTexts");

local time = time;
local format, join = string.format, string.join;

local GetGameTime = GetGameTime;
local GetNumSavedInstances = GetNumSavedInstances;
local GetSavedInstanceInfo = GetSavedInstanceInfo;
local SecondsToTime = SecondsToTime;

local timeDisplayFormat = "";
local dateDisplayFormat = "";
local europeDisplayFormat_nocolor = join("", "%02d", ":|r%02d");
local lockoutInfoFormatNoEnc = "%s%s |cffaaaaaa(%s)";
local difficultyInfo = {"N", "N", "H", "H"};
local lockoutColorExtended, lockoutColorNormal = {r = 0.3, g = 1, b = 0.3}, {r = .8, g = .8, b = .8};

local function OnClick(_, btn)
	if(btn == "RightButton") then
		if(not IsAddOnLoaded("Blizzard_TimeManager")) then LoadAddOn("Blizzard_TimeManager"); end
		TimeManagerClockButton_OnClick(TimeManagerClockButton);
	else
		GameTimeFrame:Click();
	end
end

local function OnLeave()
	DT.tooltip:Hide();
end

local function OnEnter(self)
	DT:SetupTooltip(self)
	
	RequestRaidInfo()

	local name, id, reset;
	local oneraid, instanceid;
	for i = 1, GetNumSavedInstances() do
		name, id, reset = GetSavedInstanceInfo(i);
		if(name) then
			if(not oneraid) then
				DT.tooltip:AddLine(" ");
				DT.tooltip:AddLine(L["Saved Raid(s)/Heroic Instance(s)"]);
				oneraid = true;
			end
			instanceid = format("%d (%s)", id, name)
			DT.tooltip:AddDoubleLine(instanceid, SecondsToTime(reset, true), 1, 1, 1, lockoutColorNormal.r, lockoutColorNormal.g, lockoutColorNormal.b);
		end
		if i == 1 then
			DT.tooltip:AddLine(" ")
		end
	end

	DT.tooltip:AddDoubleLine(TIMEMANAGER_TOOLTIP_REALMTIME, format(europeDisplayFormat_nocolor, GetGameTime()), 1, 1, 1, lockoutColorNormal.r, lockoutColorNormal.g, lockoutColorNormal.b);

	DT.tooltip:Show();
end

local lastPanel;
local int = 5;
local function OnUpdate(self, t)
	int = int - t;

	if(int > 0) then return; end

	self.text:SetText(BetterDate(E.db.datatexts.timeFormat .. " " .. E.db.datatexts.dateFormat, time()):gsub(":", timeDisplayFormat):gsub("%s", dateDisplayFormat));

	lastPanel = self;
	int = 1;
end

local function ValueColorUpdate(hex)
	timeDisplayFormat = join("", hex, ":|r");
	dateDisplayFormat = join("", hex, " ");

	if(lastPanel ~= nil) then
		OnUpdate(lastPanel, 20000);
	end
end
E["valueColorUpdateFuncs"][ValueColorUpdate] = true;

DT:RegisterDatatext("Time", nil, nil, OnUpdate, OnClick, OnEnter, OnLeave);`

**Comment by fatlus** [comment]
I changed one line because it looks better:
			instanceid = format("%s (%d)", name, id)

**Comment by Tremolo4** [comment]
You should really create a pull request for code changes :)

**Comment by fatlus** [comment]
Maybe when the devs will return to this project

**Comment by Tremolo4** [comment]
It would also be easier to test / use for other people (like me) if there was a pull request instead of having to do manual copypasta 😉
