### ISSUE TITLE
Context menu font size doesn't scale with ElvUI font size

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#379]
Instead of the WotLK-Version, the Contextmenues font sizes (for example rightclick on guild datatext) doesn't scale with the ElvUI settings. If you play with a lower UI scale it looks very ugly.

**Comment by fatlus** [comment]
Since the latest updates, the font size of Ace addons menues is very tiny.
For example the dropdown menu of Atlasloot.
![wowscrnshot_121618_120220](https://user-images.githubusercontent.com/6052285/50052833-ad582500-012a-11e9-840c-e868649602de.jpg)

**Comment by Apollyonn** [comment]
https://github.com/ElvUI-TBC/ElvUI_AddOnSkins/commit/5829a11ba2559288c92c1e7815687dbd26c1e4ab
