### ISSUE TITLE
[Feature Request] Aura Bars - Friendly Aura Type "Buffs And Debuffs" Option

### ISSUE THREAD

**Issue by Fanquar** [ElvUI-TBC/ElvUI#390]
it would be incredibly helpful in pve tanking and pvp, if aura bars for both buffs and debuffs were able to be shown above player frame for an easy and intuitive view over what current cooldowns are active and what, if any, debuffs are applied *to the player* and when they will end

edit: clarity

**Comment by fatlus** [comment]
You can assign the target player aurabars to the player frame.
Unitframes -> Targetframe -> Aurabars -> Attach to Player Frame Aura Bars

**Comment by Fanquar** [comment]
what I meant is for example (in Karazhan) Moroes does his bleed, that doesn't show up on Enhanced's "Lose Control", and the Waiters with brittle bones debuff, there's all sorts of non-CC debuffs applied to the player I would want to keep track of without having to actually look away from the middle of my screen onto a side and look at what number value it has

**Comment by Apollyonn** [comment]
![wowscrnshot_091318_080219](https://user-images.githubusercontent.com/19589902/45468161-f06dbb00-b72b-11e8-8370-1bbe72413b4b.jpg)

**Comment by Fanquar** [comment]
okay so here's a poorly edited pic of what I'd like to see...
![screenshot_5](https://user-images.githubusercontent.com/41789276/45472395-65dd8980-b734-11e8-86d4-8b72ee971acd.jpg)

**Comment by Apollyonn** [comment]
If i undertand correctly you want the enemy debuffs (aurabars) that you applied to show above your aurabars. This is already possible.
![wowscrnshot_091318_112315](https://user-images.githubusercontent.com/19589902/45476393-7b0fe380-b747-11e8-9ec7-024df35777e0.jpg)

![1](https://user-images.githubusercontent.com/19589902/45476576-ed80c380-b747-11e8-95cc-18eb4b17ed86.jpg)
![2](https://user-images.githubusercontent.com/19589902/45476579-efe31d80-b747-11e8-87f1-aef63ba74a99.jpg)
![3](https://user-images.githubusercontent.com/19589902/45476582-f2457780-b747-11e8-96e6-90e782274105.jpg)
