### ISSUE TITLE
GM Ticket Frame not moving actual ticket frame Y coordinate

### ISSUE THREAD

**Issue by Fanquar** [ElvUI-TBC/ElvUI#391]
"pre" view: ![screenshot_5](https://user-images.githubusercontent.com/41789276/45417756-31f65b80-b683-11e8-99c1-da5e6454dc0b.png)

post X-coord move and /reloadUI: ![screenshot_6](https://user-images.githubusercontent.com/41789276/45418157-0fb10d80-b684-11e8-94fd-13058b1fa606.png)

post Y-coord move and /reloadUI: ![screenshot_7](https://user-images.githubusercontent.com/41789276/45418388-a5e53380-b684-11e8-9ddd-50241d987636.png)

**Comment by Apollyonn** [comment]
Works fine for me. https://i.gyazo.com/b49b1074c18ee1041ddeb57ddb7a6f3c.mp4
