### ISSUE TITLE
Complete profile reset when logging/quit with multiple accounts

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#396]
I receive a full profile reset of all chars if I log into a char during close another one on the realm. Back2Basics provide 3 sub accounts of a main account (LOGINNAME-1 to -3) which allows to play 3 chars parallel. When I login a char on the -1 account during log off a from -3, all ElvUI profiles are resetted. This affects only ElvUI. All other addons make no problems.

**Comment by Apollyonn** [comment]
Yeah, i don't know if we can fix that since it might require a lot of changes to support this.
