### ISSUE TITLE
I can't do /played

### ISSUE THREAD

**Issue by Erodraeda** [ElvUI-TBC/ElvUI#397]
Whenever I do /played with ElvUI Chat activated, it doesn't work. Nothing happens, that is. Whenever I disable either ElvUI or it's chat, it works normally. And it's not problems with compatibility, because I tried with no addons but elvui enabled.

**Comment by Sp5rky** [comment]
I think this has something to do with the elvui chat, If you disable the elvui chat and use Prat/(any of the others) /played works fine within Elvui.

**Comment by Jezofine** [comment]
I can confirm that /played is not working with ElvUI chat module enabled. If you disable only chat module it works fine.
