### ISSUE TITLE
No roll screen

### ISSUE THREAD

**Issue by MeowStonetalon** [ElvUI-TBC/ElvUI#40]
I am not getting the window to pop up when loot is being rolled for.

**Comment by crumdidlyumshis** [comment]
Hmm, its working for me. Could you explain further what you did?

**Comment by MeowStonetalon** [comment]
I was raiding MC for bindings and there was never a window to roll for loot that drops

**Comment by MeowStonetalon** [comment]
Haven't tested if it is a raid issue though

**Comment by crumdidlyumshis** [comment]
Maybe the loot was set to master loot? I think that's how it should work if so. I'll try to check as well when I get time.

**Comment by crumdidlyumshis** [comment]
Closing for now. I haven't had any issues. Let me know if you come across anymore, i'll re-open this if needed.
