### ISSUE TITLE
Profession frames clipping

### ISSUE THREAD

**Issue by Fanquar** [ElvUI-TBC/ElvUI#402]
when having chat window open and opening a profession, this happens:
![image](https://user-images.githubusercontent.com/41789276/46580324-e38a7180-ca22-11e8-99c2-c3b89edcf4ca.png) 

also, annoyingly, happens with trade window + profession, making enchanting an item in trade a bit of a pain

**Comment by Apollyonn** [comment]
Unable to reproduce.
https://i.gyazo.com/b128bf5368ebbd960f45761de552f617.mp4

**Comment by Fanquar** [comment]
possibly only with the modified character frame from a plugin, I guess

**Comment by fatlus** [comment]
I think it depends on the resolution. All resolutions unter 1920x1080 don't allow two widescreen frames together like the enhanced char window and the profession window.
