### ISSUE TITLE
No config entry for auto sell greys to vendor

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#405]
The ElvUI-Config entry for autoselling grey items to the vendor is missing. Chars which had enabled this feature in an old version can auto sell greys but new chars haven't this option.

**Comment by fatlus** [comment]
In addition to this: Since a few versions the auto sell function works very slow. It appears a small red progress bar in the middle of the screen and the grey items were selling one by one. In the older version all grey items were sold instantly without the red progress bar.

**Comment by Apollyonn** [comment]
![bc534118c95700ef1a6c15e2adf5e09c](https://user-images.githubusercontent.com/19589902/47348319-e095af00-d6b9-11e8-8472-2f1c6cd953c1.png)

**Comment by fatlus** [comment]
Oh well, doesn't know the feature was moved from general to bags. My fault.
