### ISSUE TITLE
Error CopyChat

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-TBC/ElvUI#411]
**When i click on the chat copy icon this error appears**

Message: Interface\AddOns\ElvUI\modules\chat\chat.lua:371: attempt to index global 'CopyChatFrame' (a nil value)
Time: 10/27/18 01:46:08
Count: 1
Stack: (tail call): ?
[C]: ?
Interface\AddOns\ElvUI\modules\chat\chat.lua:371: in function `CopyChat'
Interface\AddOns\ElvUI\modules\chat\chat.lua:283: in function <Interface\AddOns\ElvUI\modules\chat\chat.lua:281>

**Comment by Apollyonn** [comment]
Can't reproduce.
