### ISSUE TITLE
[Feature Request] Overall transparency settings Omen - Recount - Scada

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-TBC/ElvUI#413]
Please add a function to ElvUI _([Addon Skins>Embed Settings](https://b.radikal.ru/b32/1810/88/02026a94ad7c.jpg
))_ - **Adjust/Customize overall transparency**
_Since at the moment it is impossible to correctly adjust the transparency settings._
Thx.

**Comment by Apollyonn** [comment]
Open the issues to the appropriate plugin section.
