### ISSUE TITLE
[Feature Request] Switch addon ElvUI interface language regardless of WoW client language

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-TBC/ElvUI#415]
Example: I have an English client, but in the ElvUI settings I can enable the display of addon settings in Russian. Various language combinations are possible.
Ty.

**Comment by Apollyonn** [comment]
https://github.com/ElvUI-TBC/ElvUI/commit/58801e7aaf32828f58f66e961b6caa9aabb59b21
