### ISSUE TITLE
Aura duration not shown on target

### ISSUE THREAD

**Issue by Denziz** [ElvUI-TBC/ElvUI#418]
Hello! I downloaded the latest version of ElvUI for the client 2.4.3 and the problem that I have at the moment is that target auras duration is not showing however my aura duration is. 

I have a few screenshots to make this a lot clearer to understand down below.

Here is two examples I used, when I have a buff (the unitframe to the left) my aura is shown with the duration inside it. However targeted players with buffs is not showing the duration of that aura but it's showing the icon but when I targed my self it is shown how I want it to be. 

![player buff show duration and target](https://user-images.githubusercontent.com/5758943/48305578-93c12d80-e52d-11e8-8e86-d8c0902b5367.PNG)

![target buff not showing duration](https://user-images.githubusercontent.com/5758943/48305582-a3d90d00-e52d-11e8-8862-c64c2c879947.PNG)

And here are my settings, they are enabled and such so I can't see why this isn't working. I have been trying to delete and reinstall the addon, delete my cache folder etc.

![playerbuffsetting](https://user-images.githubusercontent.com/5758943/48305587-bc492780-e52d-11e8-813d-aadff672aea1.PNG)

![targetbuffsetting](https://user-images.githubusercontent.com/5758943/48305589-beab8180-e52d-11e8-9a8e-9570bb94d32d.PNG)

I just wanted to also say that this addon rocks and I love it, really appreciate you guys made this addon work for TBC client!

Kind regards, Kasper.

**Comment by fatlus** [comment]
This isn't ElvUI fault. This are the TBC mechanics. Non player based (de)buff-timer were introduced with WotLK. There is an addon for TBC named "BuffLib" (search google if interested) which can display these timer but it works only in arena because of data throttling and Threadmeter blocking.

**Comment by Denziz** [comment]
Ooh I reckon it was working before but I enabled the original Blizzard unitframes and you are indeed correct, I can't see the buff duration of the target with ElvUI disabled.
