### ISSUE TITLE
Target Frame Debuffs

### ISSUE THREAD

**Issue by lishpeth** [ElvUI-TBC/ElvUI#42]
On target frame my debuffs are not showing up when show only mine on enemy filter is checked. I unchecked to be able to see my debuffs but the debuffs are black and white as if they are not mine... It should be colored as default, I should see the debuffs if I check the show only mine. If I uncheck show only mine, my debuffs should be colored as normal and other players'  debuffs should be black and white...

**Comment by Pziko** [comment]
bump
