### ISSUE TITLE
Unlock Chat edit Box

### ISSUE THREAD

**Issue by JamesCutter** [ElvUI-TBC/ElvUI#421]
I cant remember how to unlock my Chat edit box. I always have mine set to be in the middle of the screen but I cannot remember how to do it. The only option I have is Below/Above Chat, Help pls

**Comment by Apollyonn** [comment]
At the moment there is no option to freely move the chat edit box, you can only anchor it at the top or botton of the chat.

**Comment by JamesCutter** [comment]
I hope this can be implemented. Im pretty sure it is in later versions because I always have my Chat Editbox in the middle of my screen.
