### ISSUE TITLE
[Bug] BigWigs Minimap Button is not showing

### ISSUE THREAD

**Issue by Denziz** [ElvUI-TBC/ElvUI#422]
Hello! When I have ElvUI activated the minimap button of BigWigs is no where to be found. I have AtlasLoot and Omen2 and they are showing perfectly but I have no idea why BigWigs is not, maybe there is something to configure to make it appear?

I'm using the latest version of ElvUI and also using the plugin minimapbuttons and it's latest version as well.

Kind Regards, Denziz.

Edit: Disabling the minimap does not work, I have tried it. In order to get the BigWigs minimap button to show up I have to disable ElvUI.

**Comment by Fanquar** [comment]
![image](https://user-images.githubusercontent.com/41789276/48786391-117ff880-ece7-11e8-837e-0558ce2d0e62.png)
delete or remove that plucker

**Comment by Denziz** [comment]
Thank you that works! But what does that folder do? I'm scared of editing files and such I hope I didn't break something by deleting that folder xD

**Comment by Fanquar** [comment]
I've got no idea, I haven't noticed anything explicitly break after removing it in the past, but maybe Apollon knows what, if anything, has a dependancy in that lib... maybe if I was better versed in github I could even figure it out?

**Comment by Denziz** [comment]
I'm not using the addon FuBar so it shouldn't break anything I suppose? Also a question about BigWigs itself, is there any way to change the message text from monochrome to thin outline? ^^

**Comment by Fanquar** [comment]
I don't use FuBar either, or BigWigs... and it isn't on AddOnSkins so... you'll have to look in BigWigs settings and pray there's options there (but since it's a tbc addon I wouldn't get your hopes up too high)

**Comment by Denziz** [comment]
Cheers mate ^^
