### ISSUE TITLE
Simple problem with filters

### ISSUE THREAD

**Issue by Xaner** [ElvUI-TBC/ElvUI#423]
Hello.
My problem is with Aura bars filters.
So.. i set up my own Whitelist filter so it would show me on the Player frame just buffs that i want to see such as commanding shout, shield wall, etc. But when i finally get my list of Whitelist Aura buffs done. Some Aura buffs that isn't on my list still showing.. i tried everything.
So i am just asking if the filters are bugged in some way let me know but if everything is working properly just give me some simple advice how to set up Aura buffs/debuffs.
I just want see my personal buffs/debuffs that i set up. Thats all.
When i played on retail like week ago, there was actually a filter button that would show just my personal buffs or debuffs.

Thanks for any kind of help or advice. It means a lot for me.

**Comment by Apollyonn** [comment]
Set Maximun duration to 0
