### ISSUE TITLE
Party Frames

### ISSUE THREAD

**Issue by TheRealestMcCoy** [ElvUI-TBC/ElvUI#425]
When I join a party my party frames dont show up. I have to go to unitframes>party frames unclick enable then reenable the to show up.

**Comment by TheRealestMcCoy** [comment]
https://gyazo.com/c1350d03eac7829e61692e4ca56e28d4

https://gyazo.com/9ab765ec6ff19996ce77f6909bbead01

https://gyazo.com/1809f362ae0f5c3a69eafd1f562ca6f8

https://gyazo.com/b7e1c9b342d5d01d10e6cf9662b24a4f

**Comment by JeanCodeVanDamme** [comment]
I have the same problem with the party units, who won't refresh on their own.
a /reload  should do the same, but it is pretty annoying that you have to do it.

**Comment by Apollyonn** [comment]
give me your profile

**Comment by Apollyonn** [comment]
Try now

**Comment by CreybeN** [comment]
have the same problem, is fixed?

**Comment by TheRealestMcCoy** [comment]
seems the issue is fixed atm.
