### ISSUE TITLE
Buff Indicator doesn't work

### ISSUE THREAD

**Issue by lishpeth** [ElvUI-TBC/ElvUI#43]
Buff Indicator on Unit Frames doesn't work. I have added old rank 12 Power Word: Shield id. Also in filters there were weakened soul debuff by default, it was not showing up, too as buff indicator in the place that is assigned. Nothing is showed up. Also, when I try to check raiddebuffs in raid debuff indicator filter, it was empty...

**Comment by kinappy** [comment]
![image](https://cloud.githubusercontent.com/assets/25764850/25971405/62e0f470-369c-11e7-801e-32294eedb65a.png)


LIke this?

The Weakend Soul is showing as Prayer of Fortitude

**Comment by crumdidlyumshis** [comment]
I'll look into this. I knew I had a few more tweaks to the auras but never got around to it.

**Comment by lishpeth** [comment]
On raid frames and party frames, there are buff indicator options for healers to recognize their spesific buffs. If I check to how buff indicator and raiddebuff indicator on raid/party frames, I should be able to see icons on those frames of my buffs like renew, rejuvenation; like this: ( a wotlk version elvui)
![wowscrnshot_052216_023719](https://cloud.githubusercontent.com/assets/28478416/26025499/c6a0b12a-37f1-11e7-9597-6cda65094234.jpg)

There were weakened soul icon in the filters as default but because of the indicators not working, that debuff wasn't there when I cast shield on myself, too. Those indictors would be colored or textured. I use textured version with display text in the screenshot. Also in filters, raiddebuff filter doesn't contain any debuffs from raids or crowdcontrols when I check, that may mean they are not added yet.
