### ISSUE TITLE
Getting an error about GetItemQualityColor

### ISSUE THREAD

**Issue by Denziz** [ElvUI-TBC/ElvUI#435]
Hello! I am getting this error when I logon into the game.

> Message: Interface\AddOns\ElvUI\modules\auras\auras.lua:257: Usage: GetItemQualityColor(index)
Time: 12/16/18 18:43:43
Count: 1
Stack: (tail call): ?
[C]: ?
[C]: in function `GetItemQualityColor'
Interface\AddOns\ElvUI\modules\auras\auras.lua:257: in function <Interface\AddOns\ElvUI\modules\auras\auras.lua:248>

**Comment by Apollyonn** [comment]
Try now

**Comment by Denziz** [comment]
No error showing up now :) Thank you so much for this fix, however minimap text location on mouseover is not working for me, but when I switch it to always show it shows up perfectly.

**Comment by Apollyonn** [comment]
![map](https://user-images.githubusercontent.com/19589902/50059563-428e0480-0191-11e9-83ce-cdc2d31a99a2.gif)
Works fine for me

**Comment by Denziz** [comment]
I figured it out, there is an addon interfering with it, disabled everything and going to enable one addon one by one however the color of the location text is different than yours, how can I change it?

![different color](https://user-images.githubusercontent.com/5758943/50059823-13c15f80-018c-11e9-8a48-5fea13ee7d8b.PNG)
