### ISSUE TITLE
Buffs not always showing on party frames

### ISSUE THREAD

**Issue by BezawitNW** [ElvUI-TBC/ElvUI#437]
I am having a very strange issue with ElvUI for TBC. My Mark of the Wild / Gift of the Wild / Thorns buffs are not showing on the party frame unless I am very far away from them (200+ yards).

Picture of the issue: https://imgur.com/a/S42HJiP - The Paladin in my group is buffed with Gift of the Wild (verified from my target frame) but GoTW is not showing up on the party frame.

Picture of ElvUI party buff settings: https://imgur.com/a/BezOCut - Note that no filters are being used

As mentioned, if I fly 200+ yards away from the party member and then reload my ui, the buff properly shows: https://imgur.com/a/ke3f0t2

But if I fly back toward the party member, the buff suddenly disappears from the party frame like in the original picture of the issue.

I have tried restarting WoW, reloading ui, disabling ALL other addons, deleting WTF and WDB folders. Even when deleting the WTF folder and going through the initial ElvUI setup, I still had the same issue. I am also using the most recent version of ElvUI for TBC- I just began using it yesterday.

**Comment by Denziz** [comment]
You have set maximum duration to 300 seconds and the buff have 47 minutes left, maybe that's why? Try dragging maximum duration to 0 and I am sure it should pop up :)

**Comment by BezawitNW** [comment]
> You have set maximum duration to 300 seconds and the buff have 47 minutes left, maybe that's why? Try dragging maximum duration to 0 and I am sure it should pop up :)
> 
> ![jzo2l8u](https://user-images.githubusercontent.com/5758943/50119027-ca3b4800-0251-11e9-85ba-81d43c8ab46a.jpg)

Wow I can't believe I missed this- I thought I had it set to 0 seconds. Thank you!
