### ISSUE TITLE
ElvUI-CustomTweak AuraIconSpacing error when dragging 'Aura Spacing' bar.

### ISSUE THREAD

**Issue by Denziz** [ElvUI-TBC/ElvUI#438]
Hello! I am very fond of the CustomTweak plugin as it has a lot of neat features however one of the favorites is not working :(

I get the error whenever I drag the aura spacing bar and even just clicking the drag button triggers it.

> Message: ...stomTweaks\Categories\Unitframes\AuraIconSpacing.lua:116: bad argument #1 to 'pairs' (table expected, got nil)
Time: 12/21/18 04:36:10
Count: 6
Stack: (tail call): ?
(tail call): ?
[C]: ?
...stomTweaks\Categories\Unitframes\AuraIconSpacing.lua:116: in function <...stomTweaks\Categories\Unitframes\AuraIconSpacing.lua:102>
...stomTweaks\Categories\Unitframes\AuraIconSpacing.lua:43: in function <...stomTweaks\Categories\Unitframes\AuraIconSpacing.lua:43>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:820: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:641>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:872: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:860>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...Ons\ElvUI_Config\Libraries\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...Libraries\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:65: in function <...Libraries\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:60>

**Comment by Apollyonn** [comment]
https://github.com/ElvUI-TBC/ElvUI_CustomTweaks/commit/f698a590d12a9e9a0ba794d562cc76fe06c8a717
