### ISSUE TITLE
Chat errors.

### ISSUE THREAD

**Issue by kaspermwh** [ElvUI-TBC/ElvUI#44]
Tradechat/LFG/custom chats show the [Language] bracket inline text. (In my case shows [Common] after every person writes something.

![image](https://cloud.githubusercontent.com/assets/7907083/25775259/44f04e6a-32a1-11e7-8af3-be2380dca303.png)

Also you cannot click a persons name to whisper that person.

And the chatframe doesnt remember which chat you were last writing in when you press the enter key. (Works for raid, guild and party chat though) but no custom chats or trade/lfg.

**Comment by crumdidlyumshis** [comment]
Yeah its still really buggy. I am still slowly leanrning about LUA more and more each day when I can. I wish I had mo knowledge in how to update better. The Chat frame is proabably the hardest thing ive had to tackle. So far its hacked-coded to work, but not fully. There is still more to update 

I think @Bunny67 and others have been either taking a break from this or are busy IRL at the moment. Waiting for them to re-write the chat will probably be the best option for now. Maybe try another chat addon in the meantime?

**Comment by kaspermwh** [comment]
Cool man. You're doing an amazing job! :) Just wanted to inform you in case you had missed the bugs.

**Comment by crumdidlyumshis** [comment]
@kaspermwh thank you! I appreciate the feedback and bug reports! Keep them coming :)

**Comment by crumdidlyumshis** [comment]
These issues have been resolved :) Update to latest.
