### ISSUE TITLE
[Request] Use alternate pet bar

### ISSUE THREAD

**Issue by zefurr** [ElvUI-TBC/ElvUI#440]
Disabling the pet bar in the config window currently seems to hide the pet bar by setting alpha to 0 and size to 0.001 px. ElvUI as a whole seems to be suppressing other pet bars and then creating it's own.

I would like to be able to use a different pet bar (for example, the default blizzard pet bar, or the Bongos pet bar). As long as ElvUI is enabled, these pet bars do not work (or work poorly)

In a previous version I was able to comment out the following **BOLDED** lines in ElvUI\modules\actionbars\actionbars.lua

(near line 280)
`function AB:ReassignBindings(event)`
`	if event == "UPDATE_BINDINGS" then`
**`		--self:UpdatePetBindings()`**
`		self:UpdateStanceBindings()`
`	end`

(near line 370)
`function AB:UpdateButtonSettings()`
`	...`
**`	--self:UpdatePetBindings()`**
`	...`
**`	--self:PositionAndSizeBarPet()`**

(near line 630)
**`--PetActionBarFrame:UnregisterAllEvents()`
`--PetActionBarFrame:Hide()`
`--PetActionBarFrame:SetParent(UIHider)`**

I also commented out the entirety of ElvUI\modules\actionbars\barPet.lua

This previously allowed me to use the Bongos3 pet bar. The latest version of ElvUI TBC (as of today), these same changes did not work, all pet bars are suppressed.

As a note, the main reason I want to use another pet bar is because the ElvUI pet bar indicates which pet modes are selected (Attack, Follow, Stay) by desaturating the button slightly. This is not obvious when compared to the default blizzard UI, which places a yellow border around the selected mode.

Consider allowing us to change the appearance of the selected pet actions and modes (Aggressive, Defensive, Passive)

**Comment by Apollyonn** [comment]
Something like this will do?
![wowscrnshot_122718_135742](https://user-images.githubusercontent.com/19589902/50479473-79f58000-09df-11e9-8854-62407585fa0b.jpg)

**Comment by Apollyonn** [comment]
https://github.com/ElvUI-TBC/ElvUI_Enhanced/commit/6a9dee2e2f28a91accfac3fffbd22e5da33cba4e

**Comment by zefurr** [comment]
Yes that would do nicely, and I would simply keep the ElvUI pet bar.

That said, other people might be interested in being able to use the pet bar from other add-ons. In the same way that the ElvUI action bars can be disabled and replaced with another action bar addon.
