### ISSUE TITLE
LibRockConfig Error with Cartographer

### ISSUE THREAD

**Issue by Niylah** [ElvUI-TBC/ElvUI#441]
I can't press on the Cartographer button on the map.
I get this error:
Message: ...grapher\libs\LibRockConfig-1.0\LibRockConfig-1.0.lua:2050: bad argument #1 to 'pairs' (table expected, got nil)
Time: 12/31/18 15:59:08
Count: 1
Stack: [C]: ?
[C]: ?
...grapher\libs\LibRockConfig-1.0\LibRockConfig-1.0.lua:2050: in function <...grapher\libs\LibRockConfig-1.0\LibRockConfig-1.0.lua:2040>
...grapher\libs\LibRockConfig-1.0\LibRockConfig-1.0.lua:2631: in function <...grapher\libs\LibRockConfig-1.0\LibRockConfig-1.0.lua:2572>
...grapher\libs\LibRockConfig-1.0\LibRockConfig-1.0.lua:745: in function `OpenConfigMenu'
Interface\AddOns\Cartographer\Cartographer.lua:339: in function <Interface\AddOns\Cartographer\Cartographer.lua:338>

I could not find the version of Cartographer, I downloaded it from here: 
https://legacy-wow.com/tbc-addons/Cartographer

I tried with only ElvUI, ElvUI_Config and Cartographer running. Once with all extra ElvUI addons and once without them.

Cartographer and Questhelper does work with ElvUI. 
BUT you can't modify Cartographer at all, and all places you visit while travelling does not "light up" and is still shown as undiscovered.

Cartographer works flawless without ElvUI running.

**Comment by Apollyonn** [comment]
https://www.wowace.com/projects/cartographer/files/298196

**Comment by Niylah** [comment]
Works thanks! 👍
