### ISSUE TITLE
Chat frame not holding position in the bottom left 

### ISSUE THREAD

**Issue by Jovzin** [ElvUI-TBC/ElvUI#443]
Hello,
I am using your latest version of ElvUI from 6th January and still the chat frame in bottom left is not holding its position.  It is whatever I do like cast a spell or guild member gets online or I open a map the chat frame will jump up a bit from its default position.  I can return it back only by clikcing with left click on top of it.  
Picture for referene: 
first pic is with chat jumped above its default position: https://imgur.com/94enkJh
second pic is after I clicked a bit above the new chat position ( a bit on top )  the chat get back to its default postiion:  https://imgur.com/5Zi8Bc1

Guys can you please fix this.  It is happeing all the time when something is happening like casting spells, guild alert, opening map, mobs attacking...

**Comment by Apollyonn** [comment]
Sis you skip the instalation?

**Comment by Jovzin** [comment]
Hello Apollyon. Not not at all. BUt I found the issue.  It was somehow conflicting iwth the default blizz settings in interface/social  I had set lock chat tabs and simple chat. Turning this off , fixed it for me and I was able even to fix my other issue to see who is looting what.  sorry to bother you,
