### ISSUE TITLE
Party frame units and action bar settings issues.  A question about raid frame units.

### ISSUE THREAD

**Issue by Jovzin** [ElvUI-TBC/ElvUI#446]
Hello team. 
I have 2 issues I want to report and one question.

1/  The setting for "Right click self cast"in action bar option is not saved.  I need to disable/enable it after each relog/logout to the game.   It is  showing as enabled when I log in to the game but it is not working until I disable/enable it again in the option of action bar tab.
2/ Same for Party unit frames and their show party pets/ targets .   After every relog/logout I have to enable and disable in party unit frames -> party pet tab and party targets tab.   Looks like the settings are not saved after logout.  Beacuse when I am in party I see the party targets even if I set in the option to disable the party targets.  But here I must say party targets are sometimes not showing. It looks like it is random. One time it is working and I do not see party targets and other time it is not working and I see party targets and have to go to options and enable/disable them. 

3/ My question is about my own hots only showing.  There should be some option/checkbox to show only my Druid HOTs on raid unit frames  but I do not see it.  Can you be so kind and tell me where exactly is this option pls ?  

Thank you 
Have a nice day.

**Comment by Apollyonn** [comment]
actionbar fixed, party targets issue already reported here https://github.com/ElvUI-TBC/ElvUI/issues/431

**Comment by Jovzin** [comment]
> 
> 
> actionbar fixed, party targets issue already reported here #431

Hello 
Thank you for the info.
And anaswer to my question about raid frames and filtering of HoTs ?   Mainly I want to see my own hots only on the target raid frame not other Druids. 
Thank you
