### ISSUE TITLE
inc. heal as text value on raidframe behind name

### ISSUE THREAD

**Issue by jacknor** [ElvUI-TBC/ElvUI#448]
Hi, is there a possible way to display the text value e.g 3k heal incoming on raidframes or if its there, how do i put it infront of the name?
greetings

edit. so that there is a green + heal inc. textvalue instead of the palyers name

**Comment by jacknor** [comment]
additonally i would like to know if there is a way to emphasize a player who takes damage with a white border as long as he/she isnt full health

**Comment by Apollyonn** [comment]
TBC API doesn't support this.
