### ISSUE TITLE
ElvUI breaks addons that add map overlays

### ISSUE THREAD

**Issue by AeroScripts** [ElvUI-TBC/ElvUI#449]
This includes cartographer and questie. Basically its because of this line
https://github.com/ElvUI-TBC/ElvUI/blob/master/ElvUI/modules/maps/worldmap.lua#L112

Calling WorldMapFrame:SetToplevel() makes the map on top of everything including the overlay frames. I made a temporary fix in questieTBC (I set SetTopLevel = function() end) but that's not ideal.

Maybe there is a better way to make sure the world map is always on top, or a way to make overlay frames on top also?

Not calling WorldMapFrame:SetToplevel() at all doesn't seem to have any negative impact on the UI, windows like the character screen can become on top of the map if you open it with the map open but that's not really an issue IMO

**Comment by Apollyonn** [comment]
I think it should be ok now.
