### ISSUE TITLE
Chat windows receiving whispers even when whispers are disabled in it

### ISSUE THREAD

**Issue by staplerx300** [ElvUI-TBC/ElvUI#452]
https://i.imgur.com/w22o4gS.jpg
https://i.imgur.com/E7sCujS.png
https://i.imgur.com/G39vrYl.png

Even reloaded the UI and it doesn't help. Only thing that could be interfering is this addon:
https://github.com/fjaros/IgnoreLevel-2.4.3

**Comment by Apollyonn** [comment]
You should report this to the author of that addon.
