### ISSUE TITLE
Away from Keyboard is spamming system messages.

### ISSUE THREAD

**Issue by Vantalim** [ElvUI-TBC/ElvUI#475]
I know this might be related to WIM, but since there is a plugin for later versions of ElvUI called Chat Tweaks that fixes this, I'm trying my luck here :)
If someone I've whispered goes AFK, my system chat will be spewing out messages about every 2 seconds informing me. Is there a way to get rid of this without turning off system messages altogether? Thanx in advance!

**Comment by fatlus** [comment]
Take a look at https://github.com/ElvUI-TBC/ElvUI/issues/299
Could be a fix for your problem

**Comment by Vantalim** [comment]
It didn't solve it, but since it's still open I'll comment there and close this one. Thanx!
