### ISSUE TITLE
UI Scaling is only set to a maximum of range 0.34 to 0.64

### ISSUE THREAD

**Issue by mxwsxr** [ElvUI-TBC/ElvUI#476]
Hi,

I have an issue. I'm using this 2.4.3 version on my TBC client. My problem is that UI Scaling is only set to a maximum of range 0.34 to 0.64.
So by having an UltraWide Monitor 3440x1440 21:9 ratio it is super super small scaled for me. I can't scale it over 0.64. I usually do 0.85 on WotLK private server and WoW Retail. Do you know if that is fixable? Thanks!
![Screenshot_1](https://user-images.githubusercontent.com/18013347/66688002-1219d880-ec85-11e9-960c-e2df804f8c33.png)

**Comment by fatlus** [comment]
Try to set up the UI scale in the config.wtf and enable write protection oft the file after the edit.

**Comment by mxwsxr** [comment]
> Try to set up the UI scale in the config.wtf and enable write protection of the file after the edit.

That didn't change anything for me. I changed the uiScale value from 0.64 to 0.85
Saved the file and enabled write protection
Restarted game and still 0.64

**Comment by fatlus** [comment]
Ok, then try this way:
- In ElvUI/Settings/Global.lua change `["minUiScale"] = 0.64,` in line 5  to `["minUiScale"] = 0.85,` as you noted
- In ElvUI_Config/General.lua change `min = 0.32, max = 0.64, step = 0.01,` in line 180 to `min = 0.32, max = 0.85, step = 0.01,` as you noted

Remove write protection of the config.wtf before.

**Comment by mxwsxr** [comment]
Awesome, this helped me! Thank you very much @fatlus
