### ISSUE TITLE
chat: bad argument #1 to 'gsub' (string expected, got nil)

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-TBC/ElvUI#49]
Now I am having this issue that I cannot seem to get across. @Bunny67 @Loaal @Apollyonn

Anytime you chat in a channel, it pops up. Update to latest.

`Message: Interface\AddOns\ElvUI\modules\chat\chat.lua:711: bad argument #1 to 'gsub' (string expected, got nil)
Time: 05/10/17 20:29:23
Count: 1
Stack: [C]: ?
[C]: ?
Interface\AddOns\ElvUI\modules\chat\chat.lua:711: in function <Interface\AddOns\ElvUI\modules\chat\chat.lua:694>
(tail call): ?
Interface\FrameXML\ChatFrame.lua:2085: in function `ChatFrame_MessageEventHandler'
Interface\FrameXML\ChatFrame.lua:1935: in function `ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>
...ace\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua:3399: in function <...ace\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua:3378>
`

**Comment by DriedChicken** [comment]
You should add a type validation of the param "msg" in CH:FindURL.
The "msg" is used in the string function gsub() to replace the url in chat with some fancy replacement text. This function will throw an error if passed a invalid type, "nil" in your case.

My suggestion:
modify the file ElvUI/ElvUI/modules/chat/chat.lua, add to line 709
```lua
if type(msg) ~= "string" then
 return false, msg, ...
end
```

**Comment by crumdidlyumshis** [comment]
Thank you so much for explaining this :D 

I totally agree, but as my experience is pretty low with LUA and my time is only limited to the evenings 1 or so hour, I am just trying to get what was coded before, working for TBC. I was hoping Bunny would re-write the chat frames completely, but it seems hes been pretty busy too. 

Thank you so much for this simple, yet wonderful fix 👍

**Comment by kinappy** [comment]
I have just run this for the past hour and have not recieved any chat errors. 

Thanks
