### ISSUE TITLE
[BUG] Box with (+/-) signal near minimap

### ISSUE THREAD

**Issue by erasem** [ElvUI-TBC/ElvUI#51]
I was testing the elvui and noticed a + signal near the mini map, life if a window was open. I dont know what causes this, tried to reset all settings but doesnt go away.

![wowscrnshot_051417_204536](https://cloud.githubusercontent.com/assets/9110977/26037190/61779e3a-38e6-11e7-9dd7-39db206f1e6b.jpg)

**Comment by crumdidlyumshis** [comment]
I had started working on backporting some of the wrath minimal tracking features into ElvUI but I might make it a different addon. I never finished. All that button does is when your tracking quests it hides and shows the quest being tracked. It's something still in the works 👍🏻

**Comment by erasem** [comment]
Oh, right the quest tracker! I forgot about that :P There is a way to disable that? 
Anyway, ty for the work so far!

**Comment by crumdidlyumshis** [comment]
Unfortunately not at the moment. I'll work a bit on that next when I get some time at my comp. busy today for mothers day :)

**Comment by Dehcimal** [comment]
Hey , just uncheck "Watch frame" in the skin section in elvui

**Comment by crumdidlyumshis** [comment]
Oh yes that is an option! Haha didn't think about that :) thanks @Dehcimal

**Comment by Dehcimal** [comment]
thanks to you sir. trying hard to help you findind out and fixing bugs as much as i can

**Comment by RoxSyf** [comment]
Thanks a lot Dehcimal, pretty decent fix to just disable the box until its fixed!

**Comment by crumdidlyumshis** [comment]
removed for now. Closing
