### ISSUE TITLE
Can't see my own whispers

### ISSUE THREAD

**Issue by rusonn** [ElvUI-TBC/ElvUI#56]
It works when I have Elvui disabled but I can only see recieved whispers when I have Elvui enabled. Maybe it's just me?

**Comment by crumdidlyumshis** [comment]
Try latest, I reverted some changes that were not working.

**Comment by rusonn** [comment]
Downloaded the latest and disabled all addons except Elvui and I still can't see my whispers :/

**Comment by crumdidlyumshis** [comment]
Hmm I'll look into this later this evening when I get home.

**Comment by RoxSyf** [comment]
Yeah I experienced the same problem yesterday!

**Comment by crumdidlyumshis** [comment]
check d2fdd56cd7cf4f99f74ba2bc6601d85b74fa59b4

**Comment by crumdidlyumshis** [comment]
Closing for now. Should be fixed.
