### ISSUE TITLE
Chess Event & Warrior Stances

### ISSUE THREAD

**Issue by snipsnipz** [ElvUI-TBC/ElvUI#57]
Having issues with changing stances and events like Chess in Kara or controlling the robot in 1K Needles.  The action bars don't swap and scrolling through other action bars there is no way to visibly see options.  You can still press 5 to move during Kara Chess but there's no way to get out or know what the buttons are otherwise.

Also, when respecing and switching battle stances sometimes the buttons can no longer be activated with the keyboard.  Relogging fixes this but still annoying.

**Comment by snipsnipz** [comment]
I should add, loving the project!  Submitting not as a complaint but as an opportunity to improve :)  Or maybe i'm just doing something wrong and need some advice.

**Comment by crumdidlyumshis** [comment]
No your doing fine! This is an issue and needs to be fixed soon. Problem is, I am super busy IRL and haven't had much time lately to learn more LUA and debug as much. I want to be able to fix this, but I need help. @Apollyonn any takes on this? Happens to both rogue and warrior for sure.

**Comment by crumdidlyumshis** [comment]
@Loaal @Apollyonn @Bunny67 Any thoughts? @anyonewhocancodebetterthanmeandknowsthisshit? I have tried myself, but my brain can't find an answer :(

**Comment by crumdidlyumshis** [comment]
Should be fixed via: a3374ed246c178065acfca280505d3911549390c

If not, please reopen.
