### ISSUE TITLE
Actionbars,Buffs,KB,Whispers,Bags

### ISSUE THREAD

**Issue by pilsi** [ElvUI-TBC/ElvUI#60]
Hi first thank you for this UI its awesome i know how hard is it !! dont give up !! :D :P

Actionbars - Buttons per row - sometimes buggy but reload fix it 

                     Backdrop Spacing - always cant set - reload,cache,wtf deleted nothing fix it.

                     Stance bar - when u change stance, bars doesn´t change idk its bug or normal on tbc.
    
         buffs - bugged tooltips i disabled buffs and use blizzards so this is fine not important to fix it.

         Keybind mode not work this say:

`Message:` Interface\AddOns\ElvUI\core\staticpopups.lua:446: attempt to index local 'frame' (a nil value)
Time: 05/23/17 23:34:00
Count: 6
Stack: (tail call): ?
Interface\AddOns\ElvUI\core\staticpopups.lua:446: in function `StaticPopupSpecial_Show'
Interface\AddOns\ElvUI\modules\actionbars\bind.lua:31: in function `ActivateBindMode'
Interface\AddOns\ElvUI_Config\actionbars.lua:413: in function <Interface\AddOns\ElvUI_Config\actionbars.lua:413>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:799: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[4]"]:9: in function <[string "safecall Dispatcher[4]"]:5>
(tail call): ?
...Ons\ElvUI_Config\Libraries\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...Libraries\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:22: in function <...Libraries\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19> ``
sry for spam :D maybe help it.

Whispers - cant see my whisps not important to fix .for me

Bags- if u enable bag bar u cant see Bag slots only keyring show up.

Ty.

**Comment by crumdidlyumshis** [comment]
Buffs are still on the list but this is a duplicate as of #43 and the rest has been fixed. Closing.
