### ISSUE TITLE
Chat Interface

### ISSUE THREAD

**Issue by DanielContreras** [ElvUI-TBC/ElvUI#64]
I don't seem to receive any whispers, system messages, and probably more through the ElvUI chat feature. This happens regardless of whether the chat options are checked off.

**Comment by crumdidlyumshis** [comment]
Should work in latest. If not, please reopen.

**Comment by DanielContreras** [comment]
Hey, it still doesn't seem to work. The only chat that seems to come through are the joined channels. Other that, no system messages. For instance, doing a /played will result in nothing.

**Comment by Bunny67** [comment]
check now

**Comment by crumdidlyumshis** [comment]
The /played doesn't work for me either.

**Comment by Bunny67** [comment]
check now
