### ISSUE TITLE
Chat error, not showing invite messages

### ISSUE THREAD

**Issue by LosowaNazwa** [ElvUI-TBC/ElvUI#67]
Message: Interface\AddOns\ElvUI\modules\chat\chat.lua:885: bad argument #1 to 'strlen' (string expected, got nil)
Time: 05/25/17 18:56:33
Count: 2
Stack: [C]: ?
[C]: ?
Interface\AddOns\ElvUI\modules\chat\chat.lua:885: in function ChatFrame_MessageEventHandler' Interface\AddOns\ElvUI\modules\chat\chat.lua:1121: in functionChatFrame_OnEvent'
Interface\AddOns\ElvUI\modules\chat\chat.lua:1127: in function <Interface\AddOns\ElvUI\modules\chat\chat.lua:1126>

This error shows up whenever i invite someone or get invited to party (yellow message does not appear on chat)

**Comment by crumdidlyumshis** [comment]
I cannot reproduce.

**Comment by Bunny67** [comment]
fixed
