### ISSUE TITLE
Action bar paging doesn't work/Bar backdrop bug

### ISSUE THREAD

**Issue by iisriin** [ElvUI-TBC/ElvUI#69]
Can't type in macro to change action bars with druid forms - accept button not working.
Also when I log out and log back in the backdrop for my 2nd actionbar is just a blank bar with no actual buttons or spells - have to disable and re-enable it for it to show

**Comment by crumdidlyumshis** [comment]
fixed: a3374ed246c178065acfca280505d3911549390c
