### ISSUE TITLE
Can't open bank with latest update.

### ISSUE THREAD

**Issue by devellio** [ElvUI-TBC/ElvUI#70]
Updated to the latest version and get this error when attempting to open my bank:

**Message**: Interface\AddOns\ElvUI\core\cooldowns.lua:118: attempt to index local 'cooldown' (a nil value)
**Time**: 05/31/17 06:47:34
**Count**: 1
**Stack**: (tail call): ?
`(tail call): ?
Interface\AddOns\ElvUI\core\cooldowns.lua:118: in function 'RegisterCooldown'
Interface\AddOns\ElvUI\modules\bags\bags.lua:515: in function 'Layout'
Interface\AddOns\ElvUI\modules\bags\bags.lua:1173: in function '?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function '?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function 'Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>`

**Comment by crumdidlyumshis** [comment]
Sorry, update to latest. I disabled the Cooldown on the bags for now until I fix it. LUA error gone for now.

**Comment by crumdidlyumshis** [comment]
Thank you @Bunny67! 🐰
