### ISSUE TITLE
First actionbar doesn't change to Stealthbar when stealthing.

### ISSUE THREAD

**Issue by Shamainy** [ElvUI-TBC/ElvUI#71]
Please, can you guys just fix this, annoying to have to download bartender in order for this to work, and it just looks plain ugly!

It doesn't work what so ever.

**Comment by crumdidlyumshis** [comment]
This issue has been posted multiple times and it is a priority. However, I personally do not have the experience to fix this. I have tried myself many different ways and have not yet succeeded. When the times comes and another developer has a fix for this, we can apply it. I'll keep trying myself. But I cannot promise you anything anytime soon.

**Comment by crumdidlyumshis** [comment]
Fixed via: a3374ed246c178065acfca280505d3911549390c
