### ISSUE TITLE
Now just action bar 1 disapears whenever you use a skill in stealth

### ISSUE THREAD

**Issue by Shamainy** [ElvUI-TBC/ElvUI#73]
So the problem now is that, when ever you using a skill that will take you out of stealth, like Cheap Shot for rogue, the actionbar visably just disapear, it's still there, can use keybinds, but it's now showing. If I restealth and unstealth again it will reapear again. 

But when ever I use a spell on a mob to get out of stealth, it just disapear and wont come back before I restealth and unstealth agian.

**Comment by QuadrozZz** [comment]
When you use the shadow form, the first bar will be hide. Can't cast spells.

**Comment by Shamainy** [comment]
Not for me, I can still use the spells that I have keybinded on the bar, but the bar itself is just visably gone. So I dont bother that much since I know what I'm pressing where, but still. would rather see it ;)

**Comment by crumdidlyumshis** [comment]
Fixed in latest. Thanks @Kafistal! 
Reopen if issues re-occur. Closing for now.
