### ISSUE TITLE
Visual Heal doesn't work

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#76]
An active Visual Heal option has no effect on all unit frames.

**Comment by fatlus** [comment]
Still not work (player and target unitframe)
![wowscrnshot_071817_164608](https://user-images.githubusercontent.com/6052285/28323340-ccd287ce-6bd8-11e7-996e-7d8244d20e49.jpg)

**Comment by Loaal** [comment]
Visual Heal status bar shows only in case unit have not full hp.
