### ISSUE TITLE
Chat player coloring doesn't work

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#78]
Cached players (checked in range or checked with Shift Click on player name in chat) should have colored names like the Prat or Chatter function.

**Comment by crumdidlyumshis** [comment]
This is in the works. It's been hell trying to get it work correctly though. I want this as bad as you :P

**Comment by crumdidlyumshis** [comment]
Well unfortunately we agreed to remove the functionality for now until maybe in the future it can be added but you can use https://github.com/TekNoLogic/teknicolor/tree/f17f3dcbb9aac13262532d3f237e8dfacded51f2 addon until then as it seems to work.

**Comment by crumdidlyumshis** [comment]
Closing for now.
