### ISSUE TITLE
errors, appears everytime I accept a quest.

### ISSUE THREAD

**Issue by ozezopowa** [ElvUI-TBC/ElvUI#84]
Message: Interface\AddOns\ElvUI\modules\chat\chat.lua:885: bad argument #1 to 'strlen' (string expected, got nil)
Time: 06/03/17 11:04:54
Count: 9
Stack: [C]: ?
[C]: ?
Interface\AddOns\ElvUI\modules\chat\chat.lua:885: in function `ChatFrame_MessageEventHandler'
Interface\AddOns\ElvUI\modules\chat\chat.lua:1118: in function `ChatFrame_OnEvent'
Interface\AddOns\ElvUI\modules\chat\chat.lua:1124: in function <Interface\AddOns\ElvUI\modules\chat\chat.lua:1123>
Message: ...DB_VendorPrices1\ItemDB_VendorPrices1_BaseObject.lua:13: ItemDB_VendorPrices1: Failed to load saved variables stub Lib-ItemDB_VendorPrices1_SavedVariables, for the following reason: MISSING. The addon will attempt to continue operating normally, but errata cannot be saved.
Time: 06/03/17 10:49:33
Count: 1
Stack: [C]: in function `error'
...DB_VendorPrices1\ItemDB_VendorPrices1_BaseObject.lua:13: in main chunk
Message: Interface\AddOns\ElvUI\modules\chat\chat.lua:885: bad argument #1 to 'strlen' (string expected, got nil)
Time: 06/03/17 10:49:33
Count: 1
Stack: (tail call): ?
[C]: ?
Interface\AddOns\ElvUI\modules\chat\chat.lua:885: in function `ChatFrame_MessageEventHandler'
Interface\AddOns\ElvUI\modules\chat\chat.lua:1416: in function `DisplayChatHistory'
Interface\AddOns\ElvUI\modules\chat\chat.lua:1512: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Bunny67** [comment]
check in last update

**Comment by Bunny67** [comment]
fixed
