### ISSUE TITLE
Chat tabs don't fade out

### ISSUE THREAD

**Issue by mxpxh2ogo** [ElvUI-TBC/ElvUI#87]
Chat tabs don't fade out when the backdrop is hidden on chat windows (with option selected). 
![screenshot 2017-06-03 11 38 04](https://cloud.githubusercontent.com/assets/29164417/26754933/b9759e96-4851-11e7-9036-dbe6d64bbd1b.png)

**Comment by crumdidlyumshis** [comment]
Seems to be working now on latest update. Closing.

**Comment by mxpxh2ogo** [comment]
Still not working for me with update, but I'll check again tomorrow. Thanks.

**Comment by crumdidlyumshis** [comment]
What option exactly are you referring to exactly?

**Comment by mxpxh2ogo** [comment]
Hi Crum :) Here is another screenshot of the issue with the chat tabs circled (for reference). When I select to hide the backdrop on the chat window (Chat>Panels>Panel Backdrop>dropdown menu> hide both) the tabs are supposed to fade out (with the option 'fade tabs no backdrop'), but they remain. I have noticed a few other bugs too, but I will open new tickets as soon as I have a chance. Appreciate all of your hard work fixing these issues (this has been my fav UI for many years). Let me know if you need more info.
![wowscrnshot_060317_113804_edit](https://cloud.githubusercontent.com/assets/29164417/26766168/f86cfb40-4959-11e7-87af-fecb192c5fd1.jpg)
