### ISSUE TITLE
Whisp to guild mates through guild datatext not working

### ISSUE THREAD

**Issue by havlicekdom** [ElvUI-TBC/ElvUI#91]
I get a LUA error when I right click guild datatext and select some guild mate to whisp.

Paste of error:

`Date: 2017-06-04 17:09:47
ID: 52
Error occured in: Global
Count: 1
Message: ..\AddOns\ElvUI\modules\datatexts\guild.lua line 132:
   attempt to concatenate local 'playerName' (a nil value)
Debug:
   [C]: ?
   ElvUI\modules\datatexts\guild.lua:132: func()
   ..\FrameXML\UIDropDownMenu.lua:555: UIDropDownMenuButton_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
AddOns:
  Compatibility, v1.0
  DebugTools, v1.0
  AtlasLoot, vAtlasLoot Enhanced v4.06.04
  AtlasLootBCInstances, v4.06.03
  AtlasLootCrafting, v4.06.03
  AtlasLootRepFactions, v4.06.03
  AtlasLootSetsandPvP, v4.06.03
  AtlasLootWorldLoot, v4.06.03
  Auctionator
  GroupCalendar, v4.1b5
  Ace2
  Ace3
  LootDB, v1.0
  Omen, vOmen r79486 / Threat-2.0 r80880
  Pawn, v1.1.2
  Postal, v2.1 r79759
  QuestHelper, v0.49
  RatingBuster, v1.3.8 (r78903)
  Recount, v100003
  SharedMedia, v3.0
  Stubby, v93
  Swatter, v5.0.0
  TekniColor, v2.4.2.4
  DBMAPI
  ElvUI, v1.20
`

**Comment by crumdidlyumshis** [comment]
Same with Friends too.
