### ISSUE TITLE
Debuff color

### ISSUE THREAD

**Issue by Suonu** [ElvUI-TBC/ElvUI#96]
My Debuffs black and white, they should be colored
http://i.imgur.com/ad7PGOn.jpg

**Comment by Shamainy** [comment]
Wierd, dont have that problem and never seen it.. No lua error or anything?

**Comment by Suonu** [comment]
No errors, they just black and white...

**Comment by Pziko** [comment]
File: ElvUI\modules\unitframes\elements\**auras.lua**
line **347**
disable the line
--	button.icon:SetDesaturated((unit and not unit:find("arena%d")) and true or false);
